// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
// Generated by tools/session-codec.cmake from tools/session-codec-schema.json.

#pragma once

#include <felitronics/session/Snapshot.h>
#include <type_traits>

namespace felitronics::session::detail
{
template <class T> constexpr unsigned enumLast() noexcept
{
    if constexpr (std::is_same_v<T, Device>)
    {
        static_assert (unsigned (Device::Hpf) == 0);
        static_assert (unsigned (Device::MonoBass) == 1);
        static_assert (unsigned (Device::Glue) == 2);
        static_assert (unsigned (Device::Saturation) == 3);
        static_assert (unsigned (Device::Tilt) == 4);
        static_assert (unsigned (Device::Limiter) == 5);
        static_assert (unsigned (Device::Dither) == 6);
        static_assert (unsigned (Device::LowShelf) == 7);
        return 7;
    }
    else if constexpr (std::is_same_v<T, Needles>)
    {
        static_assert (unsigned (Needles::Auto) == 0);
        static_assert (unsigned (Needles::Manual) == 1);
        static_assert (unsigned (Needles::Off) == 2);
        return 2;
    }
    else if constexpr (std::is_same_v<T, PhaseName>)
    {
        static_assert (unsigned (PhaseName::Stream) == 0);
        static_assert (unsigned (PhaseName::Report) == 1);
        static_assert (unsigned (PhaseName::Analyzers) == 2);
        static_assert (unsigned (PhaseName::Pass) == 3);
        static_assert (unsigned (PhaseName::Remeasure) == 4);
        static_assert (unsigned (PhaseName::Convert) == 5);
        static_assert (unsigned (PhaseName::Lra) == 6);
        static_assert (unsigned (PhaseName::Final) == 7);
        return 7;
    }
    else if constexpr (std::is_same_v<T, State>)
    {
        static_assert (unsigned (State::Empty) == 0);
        static_assert (unsigned (State::Loaded) == 1);
        static_assert (unsigned (State::Measured1) == 2);
        static_assert (unsigned (State::Measured2) == 3);
        return 3;
    }
    else static_assert (std::is_same_v<T, void>, "enum missing from codec description");
}

constexpr void checkEnum (Device value) noexcept
{
    switch (value)
    {
        case Device::Hpf: break;
        case Device::MonoBass: break;
        case Device::Glue: break;
        case Device::Saturation: break;
        case Device::Tilt: break;
        case Device::Limiter: break;
        case Device::Dither: break;
        case Device::LowShelf: break;
    }
}

constexpr void checkEnum (Needles value) noexcept
{
    switch (value)
    {
        case Needles::Auto: break;
        case Needles::Manual: break;
        case Needles::Off: break;
    }
}

constexpr void checkEnum (PhaseName value) noexcept
{
    switch (value)
    {
        case PhaseName::Stream: break;
        case PhaseName::Report: break;
        case PhaseName::Analyzers: break;
        case PhaseName::Pass: break;
        case PhaseName::Remeasure: break;
        case PhaseName::Convert: break;
        case PhaseName::Lra: break;
        case PhaseName::Final: break;
    }
}

constexpr void checkEnum (State value) noexcept
{
    switch (value)
    {
        case State::Empty: break;
        case State::Loaded: break;
        case State::Measured1: break;
        case State::Measured2: break;
    }
}

template <class V, class T> void describe (V& v, T& x) noexcept
{
    using U = std::remove_cv_t<T>;
    if constexpr (std::is_same_v<U, Devices>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.dither)>, Layers<DitherFields>>);
        v.field ("dither", x.dither);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.glue)>, Layers<GlueFields>>);
        v.field ("glue", x.glue);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hpf)>, Layers<HpfFields>>);
        v.field ("hpf", x.hpf);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.limiter)>, Layers<LimiterFields>>);
        v.field ("limiter", x.limiter);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.lowShelf)>, Layers<LowShelfFields>>);
        v.field ("lowShelf", x.lowShelf);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.monoBass)>, Layers<MonoBassFields>>);
        v.field ("monoBass", x.monoBass);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.saturation)>, Layers<SaturationFields>>);
        v.field ("saturation", x.saturation);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.tilt)>, Layers<TiltFields>>);
        v.field ("tilt", x.tilt);
    }
    else if constexpr (std::is_same_v<U, Layers<DitherFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, DitherFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, DitherFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, DitherFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, DitherFields<Value>>)
    {
        [[maybe_unused]] auto& [f0] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, Layers<GlueFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, GlueFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, GlueFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, GlueFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.upToDb)>, std::optional<double>>);
        v.field ("upToDb", x.upToDb);
    }
    else if constexpr (std::is_same_v<U, GlueFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.upToDb)>, double>);
        v.field ("upToDb", x.upToDb);
    }
    else if constexpr (std::is_same_v<U, Layers<HpfFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, HpfFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, HpfFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, HpfFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, std::optional<double>>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.slope)>, std::optional<std::int32_t>>);
        v.field ("slope", x.slope);
    }
    else if constexpr (std::is_same_v<U, HpfFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, double>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.slope)>, std::int32_t>);
        v.field ("slope", x.slope);
    }
    else if constexpr (std::is_same_v<U, Kept>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.id)>, std::uint32_t>);
        v.field ("id", x.id);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.recipe)>, Recipe>);
        v.field ("recipe", x.recipe);
    }
    else if constexpr (std::is_same_v<U, Layers<LimiterFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, LimiterFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, LimiterFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, LimiterFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needles)>, std::optional<Needles>>);
        v.field ("needles", x.needles);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesDb)>, std::optional<double>>);
        v.field ("needlesDb", x.needlesDb);
    }
    else if constexpr (std::is_same_v<U, LimiterFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needles)>, Needles>);
        v.field ("needles", x.needles);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesDb)>, double>);
        v.field ("needlesDb", x.needlesDb);
    }
    else if constexpr (std::is_same_v<U, Layers<LowShelfFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, LowShelfFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, LowShelfFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, LowShelfFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, std::optional<double>>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, LowShelfFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, double>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, MachineDifference>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.coreValue)>, double>);
        v.field ("coreValue", x.coreValue);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.device)>, Device>);
        v.field ("device", x.device);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.field)>, std::uint8_t>);
        v.field ("field", x.field);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fileValue)>, double>);
        v.field ("fileValue", x.fileValue);
    }
    else if constexpr (std::is_same_v<U, Layers<MonoBassFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, MonoBassFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, MonoBassFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, MonoBassFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, std::optional<double>>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.width)>, std::optional<double>>);
        v.field ("width", x.width);
    }
    else if constexpr (std::is_same_v<U, MonoBassFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, double>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.width)>, double>);
        v.field ("width", x.width);
    }
    else if constexpr (std::is_same_v<U, Phase>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.completedUnits)>, std::uint32_t>);
        v.field ("completedUnits", x.completedUnits);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fraction)>, double>);
        v.field ("fraction", x.fraction);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, PhaseName>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.pass)>, std::uint32_t>);
        v.field ("pass", x.pass);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.totalPasses)>, std::uint32_t>);
        v.field ("totalPasses", x.totalPasses);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.totalUnits)>, std::uint32_t>);
        v.field ("totalUnits", x.totalUnits);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.weightsVersion)>, std::uint64_t>);
        v.field ("weightsVersion", x.weightsVersion);
    }
    else if constexpr (std::is_same_v<U, Project>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.core)>, Version>);
        v.field ("core", x.core);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.devices)>, Devices>);
        v.field ("devices", x.devices);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.manual)>, bool>);
        v.field ("manual", x.manual);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.target)>, std::uint16_t>);
        v.field ("target", x.target);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.targetEdit)>, TargetFields<Touched>>);
        v.field ("targetEdit", x.targetEdit);
    }
    else if constexpr (std::is_same_v<U, ReadingPoint>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.index)>, std::uint64_t>);
        v.field ("index", x.index);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.value)>, double>);
        v.field ("value", x.value);
    }
    else if constexpr (std::is_same_v<U, ReadingRun>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.count)>, std::uint64_t>);
        v.field ("count", x.count);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.first)>, std::uint64_t>);
        v.field ("first", x.first);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.value)>, double>);
        v.field ("value", x.value);
    }
    else if constexpr (std::is_same_v<U, Recipe>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.project)>, Project>);
        v.field ("project", x.project);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sound)>, std::uint64_t>);
        v.field ("sound", x.sound);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.source)>, std::uint64_t>);
        v.field ("source", x.source);
    }
    else if constexpr (std::is_same_v<U, Layers<SaturationFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, SaturationFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, SaturationFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, SaturationFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.drive)>, std::optional<double>>);
        v.field ("drive", x.drive);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mix)>, std::optional<double>>);
        v.field ("mix", x.mix);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.output)>, std::optional<double>>);
        v.field ("output", x.output);
    }
    else if constexpr (std::is_same_v<U, SaturationFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.drive)>, double>);
        v.field ("drive", x.drive);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mix)>, double>);
        v.field ("mix", x.mix);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.output)>, double>);
        v.field ("output", x.output);
    }
    else if constexpr (std::is_same_v<U, SnapshotView>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.integratedLufs)>, double>);
        v.field ("integratedLufs", x.integratedLufs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.job)>, std::uint32_t>);
        v.field ("job", x.job);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.jobRecipe)>, Recipe>);
        v.field ("jobRecipe", x.jobRecipe);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machineDifferences)>, std::span<const MachineDifference>>);
        v.field ("machineDifferences", x.machineDifferences);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.masterProgress)>, Phase>);
        v.field ("masterProgress", x.masterProgress);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mastering)>, bool>);
        v.field ("mastering", x.mastering);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.masters)>, std::span<const Kept>>);
        v.field ("masters", x.masters);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementJob)>, std::uint32_t>);
        v.field ("measurementJob", x.measurementJob);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementProgress)>, Phase>);
        v.field ("measurementProgress", x.measurementProgress);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.momentary)>, std::span<const ReadingPoint>>);
        v.field ("momentary", x.momentary);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.offeredDevices)>, std::uint32_t>);
        v.field ("offeredDevices", x.offeredDevices);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.project)>, Project>);
        v.field ("project", x.project);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.revision)>, std::uint64_t>);
        v.field ("revision", x.revision);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.runs)>, std::span<const ReadingRun>>);
        v.field ("runs", x.runs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.shortTerm)>, std::span<const ReadingPoint>>);
        v.field ("shortTerm", x.shortTerm);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.source)>, Source>);
        v.field ("source", x.source);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sourceBytes)>, double>);
        v.field ("sourceBytes", x.sourceBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.state)>, State>);
        v.field ("state", x.state);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.target)>, std::string_view>);
        v.field ("target", x.target);
    }
    else if constexpr (std::is_same_v<U, Source>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.bitDepth)>, std::uint8_t>);
        v.field ("bitDepth", x.bitDepth);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.channels)>, std::uint32_t>);
        v.field ("channels", x.channels);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fileRate)>, std::uint32_t>);
        v.field ("fileRate", x.fileRate);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.frames)>, std::uint64_t>);
        v.field ("frames", x.frames);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hash)>, std::uint64_t>);
        v.field ("hash", x.hash);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, std::string_view>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.rateKnown)>, bool>);
        v.field ("rateKnown", x.rateKnown);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sampleRate)>, std::uint32_t>);
        v.field ("sampleRate", x.sampleRate);
    }
    else if constexpr (std::is_same_v<U, TargetFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.lufs)>, std::optional<double>>);
        v.field ("lufs", x.lufs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.tp)>, std::optional<double>>);
        v.field ("tp", x.tp);
    }
    else if constexpr (std::is_same_v<U, Layers<TiltFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, TiltFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, TiltFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, TiltFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, std::optional<double>>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, TiltFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, double>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, Version>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.major)>, std::uint32_t>);
        v.field ("major", x.major);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.minor)>, std::uint32_t>);
        v.field ("minor", x.minor);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.patch)>, std::uint32_t>);
        v.field ("patch", x.patch);
    }
    else static_assert (std::is_same_v<U, void>, "type missing from codec description");
}
} // namespace felitronics::session::detail
