// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
// Generated by tools/session-codec.cmake from tools/session-codec-schema.json.

#pragma once

#include <felitronics/session/Snapshot.h>
#include <type_traits>

namespace felitronics::session::detail
{
template <class T> constexpr unsigned enumLast() noexcept
{
    if constexpr (std::is_same_v<T, Analyzer>)
    {
        static_assert (unsigned (Analyzer::Loudness) == 0);
        static_assert (unsigned (Analyzer::Clipping) == 1);
        static_assert (unsigned (Analyzer::Programme) == 2);
        static_assert (unsigned (Analyzer::LowEnd) == 3);
        static_assert (unsigned (Analyzer::InfraLow) == 4);
        static_assert (unsigned (Analyzer::Forensics) == 5);
        static_assert (unsigned (Analyzer::Stereo) == 6);
        static_assert (unsigned (Analyzer::Waveform) == 7);
        static_assert (unsigned (Analyzer::StereoBursts) == 8);
        static_assert (unsigned (Analyzer::Crest) == 9);
        static_assert (unsigned (Analyzer::Hum) == 10);
        static_assert (unsigned (Analyzer::Tempo) == 11);
        static_assert (unsigned (Analyzer::Excursions) == 12);
        static_assert (unsigned (Analyzer::LowEnd150) == 13);
        return 13;
    }
    else if constexpr (std::is_same_v<T, Device>)
    {
        static_assert (unsigned (Device::Hpf) == 0);
        static_assert (unsigned (Device::MonoBass) == 1);
        static_assert (unsigned (Device::Glue) == 2);
        static_assert (unsigned (Device::Saturation) == 3);
        static_assert (unsigned (Device::Tilt) == 4);
        static_assert (unsigned (Device::Limiter) == 5);
        static_assert (unsigned (Device::Dither) == 6);
        static_assert (unsigned (Device::Low) == 7);
        return 7;
    }
    else if constexpr (std::is_same_v<T, MeasurementReason>)
    {
        static_assert (unsigned (MeasurementReason::None) == 0);
        static_assert (unsigned (MeasurementReason::Pending) == 1);
        static_assert (unsigned (MeasurementReason::Cancelled) == 2);
        static_assert (unsigned (MeasurementReason::Unsupported) == 3);
        static_assert (unsigned (MeasurementReason::TooShort) == 4);
        static_assert (unsigned (MeasurementReason::NonFinite) == 5);
        static_assert (unsigned (MeasurementReason::Capacity) == 6);
        static_assert (unsigned (MeasurementReason::NoSignal) == 7);
        static_assert (unsigned (MeasurementReason::NotImplemented) == 8);
        static_assert (unsigned (MeasurementReason::NeedNotAbove3) == 9);
        static_assert (unsigned (MeasurementReason::Memory) == 10);
        return 10;
    }
    else if constexpr (std::is_same_v<T, MeasurementStatus>)
    {
        static_assert (unsigned (MeasurementStatus::Pending) == 0);
        static_assert (unsigned (MeasurementStatus::Ready) == 1);
        static_assert (unsigned (MeasurementStatus::Unavailable) == 2);
        static_assert (unsigned (MeasurementStatus::Cancelled) == 3);
        return 3;
    }
    else if constexpr (std::is_same_v<T, Needles>)
    {
        static_assert (unsigned (Needles::Auto) == 0);
        static_assert (unsigned (Needles::Manual) == 1);
        static_assert (unsigned (Needles::Off) == 2);
        return 2;
    }
    else if constexpr (std::is_same_v<T, PhaseName>)
    {
        static_assert (unsigned (PhaseName::Stream) == 0);
        static_assert (unsigned (PhaseName::Report) == 1);
        static_assert (unsigned (PhaseName::Analyzers) == 2);
        static_assert (unsigned (PhaseName::Pass) == 3);
        static_assert (unsigned (PhaseName::Remeasure) == 4);
        static_assert (unsigned (PhaseName::Convert) == 5);
        static_assert (unsigned (PhaseName::Lra) == 6);
        static_assert (unsigned (PhaseName::Final) == 7);
        return 7;
    }
    else if constexpr (std::is_same_v<T, State>)
    {
        static_assert (unsigned (State::Empty) == 0);
        static_assert (unsigned (State::Loaded) == 1);
        static_assert (unsigned (State::Measured1) == 2);
        static_assert (unsigned (State::Measured2) == 3);
        static_assert (unsigned (State::MeasurementStopped) == 4);
        return 4;
    }
    else static_assert (std::is_same_v<T, void>, "enum missing from codec description");
}

constexpr void checkEnum (Analyzer value) noexcept
{
    switch (value)
    {
        case Analyzer::Loudness: break;
        case Analyzer::Clipping: break;
        case Analyzer::Programme: break;
        case Analyzer::LowEnd: break;
        case Analyzer::InfraLow: break;
        case Analyzer::Forensics: break;
        case Analyzer::Stereo: break;
        case Analyzer::Waveform: break;
        case Analyzer::StereoBursts: break;
        case Analyzer::Crest: break;
        case Analyzer::Hum: break;
        case Analyzer::Tempo: break;
        case Analyzer::Excursions: break;
        case Analyzer::LowEnd150: break;
    }
}

constexpr void checkEnum (Device value) noexcept
{
    switch (value)
    {
        case Device::Hpf: break;
        case Device::MonoBass: break;
        case Device::Glue: break;
        case Device::Saturation: break;
        case Device::Tilt: break;
        case Device::Limiter: break;
        case Device::Dither: break;
        case Device::Low: break;
    }
}

constexpr void checkEnum (MeasurementReason value) noexcept
{
    switch (value)
    {
        case MeasurementReason::None: break;
        case MeasurementReason::Pending: break;
        case MeasurementReason::Cancelled: break;
        case MeasurementReason::Unsupported: break;
        case MeasurementReason::TooShort: break;
        case MeasurementReason::NonFinite: break;
        case MeasurementReason::Capacity: break;
        case MeasurementReason::NoSignal: break;
        case MeasurementReason::NotImplemented: break;
        case MeasurementReason::NeedNotAbove3: break;
        case MeasurementReason::Memory: break;
    }
}

constexpr void checkEnum (MeasurementStatus value) noexcept
{
    switch (value)
    {
        case MeasurementStatus::Pending: break;
        case MeasurementStatus::Ready: break;
        case MeasurementStatus::Unavailable: break;
        case MeasurementStatus::Cancelled: break;
    }
}

constexpr void checkEnum (Needles value) noexcept
{
    switch (value)
    {
        case Needles::Auto: break;
        case Needles::Manual: break;
        case Needles::Off: break;
    }
}

constexpr void checkEnum (PhaseName value) noexcept
{
    switch (value)
    {
        case PhaseName::Stream: break;
        case PhaseName::Report: break;
        case PhaseName::Analyzers: break;
        case PhaseName::Pass: break;
        case PhaseName::Remeasure: break;
        case PhaseName::Convert: break;
        case PhaseName::Lra: break;
        case PhaseName::Final: break;
    }
}

constexpr void checkEnum (State value) noexcept
{
    switch (value)
    {
        case State::Empty: break;
        case State::Loaded: break;
        case State::Measured1: break;
        case State::Measured2: break;
        case State::MeasurementStopped: break;
    }
}

template <class V, class T> void describe (V& v, T& x) noexcept
{
    using U = std::remove_cv_t<T>;
    if constexpr (std::is_same_v<U, Devices>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.dither)>, Layers<DitherFields>>);
        v.field ("dither", x.dither);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.glue)>, Layers<GlueFields>>);
        v.field ("glue", x.glue);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hpf)>, Layers<HpfFields>>);
        v.field ("hpf", x.hpf);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.limiter)>, Layers<LimiterFields>>);
        v.field ("limiter", x.limiter);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.low)>, Layers<LowFields>>);
        v.field ("low", x.low);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.monoBass)>, Layers<MonoBassFields>>);
        v.field ("monoBass", x.monoBass);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.saturation)>, Layers<SaturationFields>>);
        v.field ("saturation", x.saturation);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.tilt)>, Layers<TiltFields>>);
        v.field ("tilt", x.tilt);
    }
    else if constexpr (std::is_same_v<U, Layers<DitherFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, DitherFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, DitherFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, DitherFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, DitherFields<Value>>)
    {
        [[maybe_unused]] auto& [f0] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, EqPoint>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, double>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hz)>, double>);
        v.field ("hz", x.hz);
    }
    else if constexpr (std::is_same_v<U, Layers<GlueFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, GlueFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, GlueFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, GlueFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.upToDb)>, std::optional<double>>);
        v.field ("upToDb", x.upToDb);
    }
    else if constexpr (std::is_same_v<U, GlueFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.upToDb)>, double>);
        v.field ("upToDb", x.upToDb);
    }
    else if constexpr (std::is_same_v<U, Layers<HpfFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, HpfFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, HpfFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, HpfFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, std::optional<double>>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.slope)>, std::optional<std::int32_t>>);
        v.field ("slope", x.slope);
    }
    else if constexpr (std::is_same_v<U, HpfFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, double>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.slope)>, std::int32_t>);
        v.field ("slope", x.slope);
    }
    else if constexpr (std::is_same_v<U, Kept>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.id)>, std::uint32_t>);
        v.field ("id", x.id);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.recipe)>, Recipe>);
        v.field ("recipe", x.recipe);
    }
    else if constexpr (std::is_same_v<U, Layers<LimiterFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, LimiterFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, LimiterFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, LimiterFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needles)>, std::optional<Needles>>);
        v.field ("needles", x.needles);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesDb)>, std::optional<double>>);
        v.field ("needlesDb", x.needlesDb);
    }
    else if constexpr (std::is_same_v<U, LimiterFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needles)>, Needles>);
        v.field ("needles", x.needles);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesDb)>, double>);
        v.field ("needlesDb", x.needlesDb);
    }
    else if constexpr (std::is_same_v<U, Layers<LowFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, LowFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, LowFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, LowFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, std::optional<double>>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, LowFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, double>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, MachineDifference>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.coreValue)>, double>);
        v.field ("coreValue", x.coreValue);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.device)>, Device>);
        v.field ("device", x.device);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.field)>, std::uint8_t>);
        v.field ("field", x.field);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fileValue)>, double>);
        v.field ("fileValue", x.fileValue);
    }
    else if constexpr (std::is_same_v<U, MeasurementArray>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.columns)>, std::uint32_t>);
        v.field ("columns", x.columns);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.complete)>, bool>);
        v.field ("complete", x.complete);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.grid)>, MeasurementGrid>);
        v.field ("grid", x.grid);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, std::string_view>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.stored)>, std::uint64_t>);
        v.field ("stored", x.stored);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.total)>, std::uint64_t>);
        v.field ("total", x.total);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.values)>, std::span<const double>>);
        v.field ("values", x.values);
    }
    else if constexpr (std::is_same_v<U, MeasurementChange>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.analyzer)>, Analyzer>);
        v.field ("analyzer", x.analyzer);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.complete)>, bool>);
        v.field ("complete", x.complete);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.framesRead)>, std::uint64_t>);
        v.field ("framesRead", x.framesRead);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.key)>, std::uint64_t>);
        v.field ("key", x.key);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.reason)>, MeasurementReason>);
        v.field ("reason", x.reason);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.revision)>, std::uint64_t>);
        v.field ("revision", x.revision);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.source)>, std::uint64_t>);
        v.field ("source", x.source);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.status)>, MeasurementStatus>);
        v.field ("status", x.status);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.stored)>, std::uint64_t>);
        v.field ("stored", x.stored);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.total)>, std::uint64_t>);
        v.field ("total", x.total);
    }
    else if constexpr (std::is_same_v<U, MeasurementGrid>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.firstFrame)>, std::uint64_t>);
        v.field ("firstFrame", x.firstFrame);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.framesRead)>, std::uint64_t>);
        v.field ("framesRead", x.framesRead);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sampleRate)>, std::uint32_t>);
        v.field ("sampleRate", x.sampleRate);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.stepFrames)>, std::uint64_t>);
        v.field ("stepFrames", x.stepFrames);
    }
    else if constexpr (std::is_same_v<U, MeasurementResult>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.analyzer)>, Analyzer>);
        v.field ("analyzer", x.analyzer);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.arrays)>, std::span<const MeasurementArray>>);
        v.field ("arrays", x.arrays);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.complete)>, bool>);
        v.field ("complete", x.complete);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.framesRead)>, std::uint64_t>);
        v.field ("framesRead", x.framesRead);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.key)>, std::uint64_t>);
        v.field ("key", x.key);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.numbers)>, std::span<const MeasurementValue>>);
        v.field ("numbers", x.numbers);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.reason)>, MeasurementReason>);
        v.field ("reason", x.reason);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.status)>, MeasurementStatus>);
        v.field ("status", x.status);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.stored)>, std::uint64_t>);
        v.field ("stored", x.stored);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.total)>, std::uint64_t>);
        v.field ("total", x.total);
    }
    else if constexpr (std::is_same_v<U, MeasurementStorage>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.allocatorBytes)>, double>);
        v.field ("allocatorBytes", x.allocatorBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.codecBytes)>, double>);
        v.field ("codecBytes", x.codecBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.copyBytes)>, double>);
        v.field ("copyBytes", x.copyBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.largestBlockBytes)>, double>);
        v.field ("largestBlockBytes", x.largestBlockBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.loadPeakBytes)>, double>);
        v.field ("loadPeakBytes", x.loadPeakBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.peakBytes)>, double>);
        v.field ("peakBytes", x.peakBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.resultBytes)>, double>);
        v.field ("resultBytes", x.resultBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sourceBytes)>, double>);
        v.field ("sourceBytes", x.sourceBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.workPeakBytes)>, double>);
        v.field ("workPeakBytes", x.workPeakBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.workspaceBytes)>, double>);
        v.field ("workspaceBytes", x.workspaceBytes);
    }
    else if constexpr (std::is_same_v<U, MeasurementValue>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.analyzerReason)>, std::uint32_t>);
        v.field ("analyzerReason", x.analyzerReason);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, std::string_view>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.reason)>, MeasurementReason>);
        v.field ("reason", x.reason);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.value)>, std::optional<double>>);
        v.field ("value", x.value);
    }
    else if constexpr (std::is_same_v<U, Layers<MonoBassFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, MonoBassFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, MonoBassFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, MonoBassFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, std::optional<double>>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.width)>, std::optional<double>>);
        v.field ("width", x.width);
    }
    else if constexpr (std::is_same_v<U, MonoBassFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fq)>, double>);
        v.field ("fq", x.fq);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.width)>, double>);
        v.field ("width", x.width);
    }
    else if constexpr (std::is_same_v<U, Phase>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.completedUnits)>, std::uint32_t>);
        v.field ("completedUnits", x.completedUnits);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fraction)>, double>);
        v.field ("fraction", x.fraction);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, PhaseName>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.pass)>, std::uint32_t>);
        v.field ("pass", x.pass);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.totalPasses)>, std::uint32_t>);
        v.field ("totalPasses", x.totalPasses);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.totalUnits)>, std::uint32_t>);
        v.field ("totalUnits", x.totalUnits);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.weightsVersion)>, std::uint64_t>);
        v.field ("weightsVersion", x.weightsVersion);
    }
    else if constexpr (std::is_same_v<U, Project>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.core)>, Version>);
        v.field ("core", x.core);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.devices)>, Devices>);
        v.field ("devices", x.devices);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.manual)>, bool>);
        v.field ("manual", x.manual);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.target)>, std::uint16_t>);
        v.field ("target", x.target);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.targetEdit)>, TargetFields<Touched>>);
        v.field ("targetEdit", x.targetEdit);
    }
    else if constexpr (std::is_same_v<U, ReadingPoint>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.index)>, std::uint64_t>);
        v.field ("index", x.index);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.value)>, double>);
        v.field ("value", x.value);
    }
    else if constexpr (std::is_same_v<U, ReadingRun>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.count)>, std::uint64_t>);
        v.field ("count", x.count);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.first)>, std::uint64_t>);
        v.field ("first", x.first);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.value)>, double>);
        v.field ("value", x.value);
    }
    else if constexpr (std::is_same_v<U, Recipe>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.project)>, Project>);
        v.field ("project", x.project);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sound)>, std::uint64_t>);
        v.field ("sound", x.sound);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.source)>, std::uint64_t>);
        v.field ("source", x.source);
    }
    else if constexpr (std::is_same_v<U, Layers<SaturationFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, SaturationFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, SaturationFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, SaturationFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.drive)>, std::optional<double>>);
        v.field ("drive", x.drive);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mix)>, std::optional<double>>);
        v.field ("mix", x.mix);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.output)>, std::optional<double>>);
        v.field ("output", x.output);
    }
    else if constexpr (std::is_same_v<U, SaturationFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.drive)>, double>);
        v.field ("drive", x.drive);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mix)>, double>);
        v.field ("mix", x.mix);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.output)>, double>);
        v.field ("output", x.output);
    }
    else if constexpr (std::is_same_v<U, SnapshotView>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26, f27, f28, f29, f30, f31, f32, f33, f34] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.canContinueMeasurement)>, bool>);
        v.optionalField ("canContinueMeasurement", x.canContinueMeasurement);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.devicesPlaced)>, bool>);
        v.field ("devicesPlaced", x.devicesPlaced);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.eqCurve)>, std::span<const EqPoint>>);
        v.field ("eqCurve", x.eqCurve);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.handFieldCount)>, std::uint32_t>);
        v.field ("handFieldCount", x.handFieldCount);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.integratedLufs)>, double>);
        v.field ("integratedLufs", x.integratedLufs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.job)>, std::uint32_t>);
        v.field ("job", x.job);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.jobRecipe)>, Recipe>);
        v.field ("jobRecipe", x.jobRecipe);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machineDifferences)>, std::span<const MachineDifference>>);
        v.field ("machineDifferences", x.machineDifferences);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mandatoryMeasurementsReady)>, bool>);
        v.field ("mandatoryMeasurementsReady", x.mandatoryMeasurementsReady);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.masterProgress)>, Phase>);
        v.field ("masterProgress", x.masterProgress);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.mastering)>, bool>);
        v.field ("mastering", x.mastering);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.masters)>, std::span<const Kept>>);
        v.field ("masters", x.masters);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementJob)>, std::uint32_t>);
        v.field ("measurementJob", x.measurementJob);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementProgress)>, Phase>);
        v.field ("measurementProgress", x.measurementProgress);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementResumeState)>, State>);
        v.optionalField ("measurementResumeState", x.measurementResumeState);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurementStorage)>, MeasurementStorage>);
        v.optionalField ("measurementStorage", x.measurementStorage);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.measurements)>, std::span<const MeasurementResult>>);
        v.optionalField ("measurements", x.measurements);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.momentary)>, std::span<const ReadingPoint>>);
        v.field ("momentary", x.momentary);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesBytes)>, double>);
        v.optionalField ("needlesBytes", x.needlesBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesCeilingDb)>, std::optional<double>>);
        v.optionalField ("needlesCeilingDb", x.needlesCeilingDb);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesJob)>, std::uint32_t>);
        v.optionalField ("needlesJob", x.needlesJob);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesLargestBlockBytes)>, double>);
        v.optionalField ("needlesLargestBlockBytes", x.needlesLargestBlockBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesNeedDb)>, std::optional<double>>);
        v.optionalField ("needlesNeedDb", x.needlesNeedDb);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesProgress)>, Phase>);
        v.optionalField ("needlesProgress", x.needlesProgress);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesRunsTruncated)>, bool>);
        v.optionalField ("needlesRunsTruncated", x.needlesRunsTruncated);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.needlesSource)>, std::uint64_t>);
        v.optionalField ("needlesSource", x.needlesSource);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.offeredDevices)>, std::uint32_t>);
        v.field ("offeredDevices", x.offeredDevices);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.project)>, Project>);
        v.field ("project", x.project);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.revision)>, std::uint64_t>);
        v.field ("revision", x.revision);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.runs)>, std::span<const ReadingRun>>);
        v.field ("runs", x.runs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.shortTerm)>, std::span<const ReadingPoint>>);
        v.field ("shortTerm", x.shortTerm);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.source)>, Source>);
        v.field ("source", x.source);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sourceBytes)>, double>);
        v.field ("sourceBytes", x.sourceBytes);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.state)>, State>);
        v.field ("state", x.state);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.target)>, std::string_view>);
        v.field ("target", x.target);
    }
    else if constexpr (std::is_same_v<U, Source>)
    {
        [[maybe_unused]] auto& [f0, f1, f2, f3, f4, f5, f6, f7] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.bitDepth)>, std::uint8_t>);
        v.field ("bitDepth", x.bitDepth);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.channels)>, std::uint32_t>);
        v.field ("channels", x.channels);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.fileRate)>, std::uint32_t>);
        v.field ("fileRate", x.fileRate);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.frames)>, std::uint64_t>);
        v.field ("frames", x.frames);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hash)>, std::uint64_t>);
        v.field ("hash", x.hash);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.name)>, std::string_view>);
        v.field ("name", x.name);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.rateKnown)>, bool>);
        v.field ("rateKnown", x.rateKnown);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.sampleRate)>, std::uint32_t>);
        v.field ("sampleRate", x.sampleRate);
    }
    else if constexpr (std::is_same_v<U, TargetFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.lufs)>, std::optional<double>>);
        v.field ("lufs", x.lufs);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.tp)>, std::optional<double>>);
        v.field ("tp", x.tp);
    }
    else if constexpr (std::is_same_v<U, Layers<TiltFields>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.hand)>, TiltFields<Touched>>);
        v.field ("hand", x.hand);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.machine)>, TiltFields<Value>>);
        v.field ("machine", x.machine);
    }
    else if constexpr (std::is_same_v<U, TiltFields<Touched>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, std::optional<double>>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, std::optional<bool>>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, TiltFields<Value>>)
    {
        [[maybe_unused]] auto& [f0, f1] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.db)>, double>);
        v.field ("db", x.db);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.on)>, bool>);
        v.field ("on", x.on);
    }
    else if constexpr (std::is_same_v<U, Version>)
    {
        [[maybe_unused]] auto& [f0, f1, f2] = x;
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.major)>, std::uint32_t>);
        v.field ("major", x.major);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.minor)>, std::uint32_t>);
        v.field ("minor", x.minor);
        static_assert (std::is_same_v<std::remove_cvref_t<decltype (x.patch)>, std::uint32_t>);
        v.field ("patch", x.patch);
    }
    else static_assert (std::is_same_v<U, void>, "type missing from codec description");
}
} // namespace felitronics::session::detail
