// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
// SESSION-LAWS CONTROL — the same placement in the GNU spelling, with the __x__ form of the attribute name.
namespace felitronics::session
{
__attribute__ ((__section__ ("__DATA,__session"))) int controlGnuState = 0;   // VIOLATION
}
