// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
// SESSION-LAWS CONTROL — a keyword split by a backslash-newline, which translation phase 2 joins before any rule reads it.
namespace felitronics::session
{
void controlSplice ();
void controlSplice () { /* // VIOLATION */ thr\
ow 1; }
}
