# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
#
# THE BANDS' NAMES, ONE LANGUAGE PER FILE: felitronics-bands keeps each language's names of the EQ bands in
# text/<code>.toml. Every such file is embedded (felitronics_toml_embed in CMakeLists.txt, toml2cpp in tools/wasm/build.sh)
# as embedded/band-text/<code>.h, and this script writes embedded/band-texts.h, the one function src/Text.cpp asks for a
# language's text. Which languages the core speaks, and that each of them has every band's name, is the text gate's to
# hold (src/TextSchema.cpp); here a file is only found.
#   cmake -DBANDS=<felitronics-bands checkout> -DOUTPUT=<embedded/band-texts.h> -P band-texts.cmake
# include()d, with BANDS and OUTPUT set, it also leaves the codes found in FELITRONICS_SESSION_BAND_LANGS.

if(NOT BANDS OR NOT OUTPUT)
    message(FATAL_ERROR "band-texts.cmake: BANDS and OUTPUT are required")
endif()
file(GLOB _band_files RELATIVE "${BANDS}/text" "${BANDS}/text/*.toml")
list(SORT _band_files)
set(FELITRONICS_SESSION_BAND_LANGS "")
set(_band_includes "")
set(_band_cases "")
foreach(_band_file IN LISTS _band_files)
    string(REGEX REPLACE "\\.toml$" "" _band_code "${_band_file}")
    if(NOT _band_code MATCHES "^[a-z][a-z]$")
        message(FATAL_ERROR "felitronics-bands: text/${_band_file} is not named for a language code")
    endif()
    list(APPEND FELITRONICS_SESSION_BAND_LANGS "${_band_code}")
    string(APPEND _band_includes "#include \"embedded/band-text/${_band_code}.h\"\n")
    string(APPEND _band_cases "    if (code == \"${_band_code}\") return ${_band_code}.root();\n")
endforeach()
if(NOT FELITRONICS_SESSION_BAND_LANGS)
    message(FATAL_ERROR "felitronics-bands at ${BANDS}: no text/<code>.toml")
endif()
file(CONFIGURE OUTPUT "${OUTPUT}" @ONLY CONTENT "// Generated by modules/session/band-texts.cmake from felitronics-bands text/*.toml — do not edit.
#pragma once
@_band_includes@
#include <felitronics/toml/Embedded.h>

#include <string_view>

namespace felitronics::session::text::embedded::bandText
{
// The names of the bands in language `code` (felitronics-bands text/<code>.toml); nothing when it has no file.
constexpr felitronics::toml::embedded::View of (std::string_view code) noexcept
{
@_band_cases@    return {};
}
} // namespace felitronics::session::text::embedded::bandText
")
