# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.

# Shadow copies, never edits to the public headers. Each drift must fail compilation; the clean twin always builds.
foreach(control clean added_field reordered_enum unknown_enum appended_State appended_Needles appended_PhaseName appended_Device)
    set(dir ${CMAKE_CURRENT_BINARY_DIR}/codec-controls/${control})
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/include/felitronics/session/Snapshot.h snapshot)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/include/felitronics/session/Commands.h commands)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/include/felitronics/session/Project.h project)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/include/felitronics/session/Events.h events)
    set(probe "static_assert (detail::enumLast<State>() == unsigned (State::MeasurementStopped));")
    if(control STREQUAL "added_field")
        string(REPLACE "double integratedLufs = 0.0;" "double integratedLufs = 0.0; double truePeakDb = 0.0;" snapshot "${snapshot}")
        set(expect "decomposes into|structured binding|C3448|C3449|elements")
    elseif(control STREQUAL "reordered_enum")
        string(REPLACE "Empty, Loaded, Measured1, Measured2" "Loaded, Empty, Measured1, Measured2" commands "${commands}")
        set(expect "static assertion|static_assert")
    elseif(control STREQUAL "unknown_enum")
        set(probe "static_assert (detail::enumLast<ErrorCode>() == 0);")
        set(expect "enum missing from codec description")
    elseif(control MATCHES "^appended_(.*)$")
        set(enum ${CMAKE_MATCH_1})
        if(enum STREQUAL "State")
            string(REPLACE "Measured2, MeasurementStopped };" "Measured2, MeasurementStopped, CodecControlAdded };" commands "${commands}")
        elseif(enum STREQUAL "Needles")
            string(REPLACE "Auto, Manual, Off" "Auto, Manual, Off, CodecControlAdded" project "${project}")
        elseif(enum STREQUAL "Device")
            string(REPLACE "Dither, Low };" "Dither, Low, CodecControlAdded };" project "${project}")
        else()
            string(REPLACE "Stream, Report, Analyzers, Pass, Remeasure" "Stream, Report, Analyzers, Pass, Remeasure, CodecControlAdded" events "${events}")
        endif()
        set(expect "CodecControlAdded.*(switch|handled)")
    endif()
    file(WRITE ${dir}/felitronics/session/Snapshot.h "${snapshot}")
    file(WRITE ${dir}/felitronics/session/Commands.h "${commands}")
    file(WRITE ${dir}/felitronics/session/Project.h "${project}")
    file(WRITE ${dir}/felitronics/session/Events.h "${events}")
    file(WRITE ${dir}/control.cpp
        "#include \"CodecSchema.h\"\nusing namespace felitronics::session;\nstruct Visitor { template<class T> void optionalField(std::string_view, const T&) {} template<class T> void field(std::string_view, T&) {} };\n${probe}\nvoid check() { Visitor v; SnapshotView x; detail::describe(v, x); }\n")
    set(target fs_codec_${control})
    if(control STREQUAL "clean")
        add_library(${target} OBJECT ${dir}/control.cpp)
    else()
        add_library(${target} OBJECT EXCLUDE_FROM_ALL ${dir}/control.cpp)
        felitronics_session_must_fail(felitronics_session_codec_control_${control} ${target} "${expect}")
    endif()
    target_compile_features(${target} PRIVATE cxx_std_20)
    target_compile_options(${target} PRIVATE $<TARGET_PROPERTY:felitronics_session,COMPILE_OPTIONS>)
    target_include_directories(${target} PRIVATE ${dir} ${CMAKE_CURRENT_SOURCE_DIR}/src ${CMAKE_CURRENT_SOURCE_DIR}/include)
endforeach()
