# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
#
# THE COMPILE LINE OF felitronics::session, READ BACK from compile_commands.json. Run by ctest:
#   cmake -DCOMPILE_COMMANDS=<compile_commands.json> -DFLAGS_FILE=<modules/session/build-flags.txt>
#         -DTARGETS=<dir>[|<dir>...] -DSOURCES=<absolute path>[|<absolute path>...] -P compile-line-gate.cmake
#
# FP contraction is the one flag no preprocessor macro announces on clang or gcc, so src/BuildGuards.h cannot refuse a
# translation unit compiled with it; and a licence like -fno-honor-nans or -ffp-model=fast defines nothing either. What
# the build ACTUALLY hands the compiler can be read, though. For every source of SOURCES — the library's units and the C
# boundary's — this requires, of each compile command that builds it into one of TARGETS (the object directory of each
# target, e.g. felitronics_session.dir):
#   * THE LIBRARY'S GROUP IS THE LAST WORD ON FLOATING POINT, EXCEPTIONS AND RTTI: the tokens of build-flags.txt appear,
#     in order, on the line, and after their last appearance no token touches floating-point semantics (-ffp-*,
#     -fno-honor-*, -fapprox-func, -fdenormal-fp-math*, -fcx-*, -mfpmath*, -fexcess-precision*, the fast-math family,
#     -Ofast ...), exceptions or RTTI. A per-source option comes after the target's on every generator, so a per-source
#     -ffp-model=fast is red here; and a group CMake de-duplicated away (a parent stated -ffp-contract=off first, and the
#     library's own was dropped — it happened) is not on the line at all, which is red too.
#   * NO FORCED INCLUDE, PASS-THROUGH, PLUGIN OR FLAG FILE anywhere on the line, in any spelling the drivers accept —
#     separated or joined: -include / -include<path> / -include-pch, --include / --include=, -imacros / -imacros<path>,
#     --imacros=, -Wp,..., every -X... (-Xclang, -Xclang=, -Xpreprocessor, -Xarch_*), -mllvm / -mllvm=, MSVC's /FI and
#     /Yu (and -FI, -Yu), clang-cl's /clang:, -fplugin*, -fpass-plugin=, -specs= / --specs=, --config*, -B<dir>. Each
#     carries flags or pragmas — or a different compiler — this gate cannot read. A RESPONSE FILE (`@file`, which the
#     emscripten toolchain uses for the include directories) is read and its tokens take its place on the line; one that
#     cannot be read is refused.
#   * EVERY SOURCE IS COMPILED into one of TARGETS, and every unit compiled into them is one of SOURCES.
# An entry is matched by its `file`; the object it builds is its `output`, or else the -o / /Fo of its command — CMake
# 3.22's Ninja and Makefile generators write no `output` field — and an entry whose object is known and lies outside
# TARGETS is another target's (a control compiling the same source with a licence appended, say) and not read.
# NOT FOR MSVC, on any generator: cl.exe announces what matters to the preprocessor (_M_FP_PRECISE, _M_FP_CONTRACT,
# _CPPUNWIND, _CPPRTTI), so src/BuildGuards.h refuses a wrong unit there with no compile line to read. The tests that
# run this are not registered on MSVC.
cmake_minimum_required(VERSION 3.22)
foreach(var COMPILE_COMMANDS FLAGS_FILE TARGETS SOURCES)
    if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
        message(FATAL_ERROR "compile-line-gate.cmake: ${var} is not set")
    endif()
endforeach()
foreach(f "${COMPILE_COMMANDS}" "${FLAGS_FILE}")
    if(NOT EXISTS "${f}")
        message(FATAL_ERROR "compile-line-gate.cmake: ${f} does not exist")
    endif()
endforeach()

file(STRINGS "${FLAGS_FILE}" group_line REGEX "^-")
list(LENGTH group_line n_group_lines)
if(NOT n_group_lines EQUAL 1)
    message(FATAL_ERROR "compile-line-gate.cmake: ${FLAGS_FILE} must hold exactly one line of flags")
endif()
separate_arguments(group UNIX_COMMAND "${group_line}")
list(LENGTH group group_n)
string(REPLACE ";" " " group_text "${group}")

string(REPLACE "|" ";" targets "${TARGETS}")
string(REPLACE "|" ";" sources_in "${SOURCES}")
set(sources "")
foreach(s IN LISTS sources_in)
    file(REAL_PATH "${s}" rs)
    list(APPEND sources "${rs}")
    string(MAKE_C_IDENTIFIER "${rs}" id)
    set(checked_${id} 0)
endforeach()

set(FP_SEMANTICS "^(-ffp-.*|-fno-fp-.*|-f(no-)?honor-.*|-f(no-)?approx-func|-fdenormal-fp-math.*|-f(no-)?cx-.*|-mfpmath.*|-fexcess-precision.*|-f(no-)?fast-math|-Ofast|-f(no-)?unsafe-math-optimizations|-f(no-)?associative-math|-f(no-)?reciprocal-math|-f(no-)?signed-zeros|-f(no-)?finite-math-only|-f(no-)?trapping-math|-f(no-)?math-errno|-f(no-)?rounding-math|-f(no-)?signaling-nans|-f(no-)?float-store|-fsingle-precision-constant|-f(no-)?protect-parens|-f(no-)?strict-float-cast-overflow|-f(no-)?(cxx-)?exceptions|-f(no-)?rtti)$")
set(UNREADABLE "^(-include.*|--include(=.*)?|-imacros.*|--imacros(=.*)?|-Wp,.*|-X.*|-mllvm(=.*)?|[/-]FI.*|[/-]Yu.*|/clang:.*|-fplugin.*|-fpass-plugin.*|-specs.*|--specs.*|--config.*|-B.*)$")

# expand_response_files <out var> <directory> <args...> — each `@file` replaced by the tokens it holds (relative to the
# entry's directory, two levels deep), or by a marker the checks below refuse when it cannot be read.
function(expand_response_files out dir)
    set(result "")
    foreach(a IN LISTS ARGN)
        if(a MATCHES "^@(.+)$")
            set(rsp "${CMAKE_MATCH_1}")
            if(NOT IS_ABSOLUTE "${rsp}")
                set(rsp "${dir}/${rsp}")
            endif()
            if(NOT EXISTS "${rsp}")
                list(APPEND result "<unreadable response file ${a}>")
                continue()
            endif()
            file(READ "${rsp}" text)
            string(REPLACE "\n" " " text "${text}")
            string(REPLACE "\r" " " text "${text}")
            separate_arguments(inner UNIX_COMMAND "${text}")
            foreach(x IN LISTS inner)
                if(x MATCHES "^@")
                    set(nested "")
                    expand_response_files(nested "${dir}" "${x}")
                    list(APPEND result ${nested})
                else()
                    string(REPLACE ";" "\\;" x "${x}")
                    list(APPEND result "${x}")
                endif()
            endforeach()
        else()
            string(REPLACE ";" "\\;" a "${a}")
            list(APPEND result "${a}")
        endif()
    endforeach()
    set(${out} "${result}" PARENT_SCOPE)
endfunction()

file(READ "${COMPILE_COMMANDS}" json)
string(JSON n LENGTH "${json}")
set(checked 0)
set(violations "")
if(n GREATER 0)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON file GET "${json}" ${i} file)
        string(JSON dir ERROR_VARIABLE nodir GET "${json}" ${i} directory)
        if(NOT IS_ABSOLUTE "${file}" AND NOT nodir)
            set(file "${dir}/${file}")
        endif()
        # the arguments: `command`, or the `arguments` array
        string(JSON cmd ERROR_VARIABLE nocmd GET "${json}" ${i} command)
        set(args "")
        if(nocmd)
            string(JSON nargs ERROR_VARIABLE noargs LENGTH "${json}" ${i} arguments)
            if(noargs)
                message(FATAL_ERROR "compile-line-gate.cmake: the entry for ${file} has neither `command` nor `arguments`")
            endif()
            if(nargs GREATER 0)
                math(EXPR lastarg "${nargs} - 1")
                foreach(k RANGE ${lastarg})
                    string(JSON a GET "${json}" ${i} arguments ${k})
                    string(REPLACE ";" "\\;" a "${a}")
                    list(APPEND args "${a}")
                endforeach()
            endif()
        else()
            separate_arguments(args UNIX_COMMAND "${cmd}")
        endif()
        # the object it builds: `output`, else -o <path> / -o<path> / /Fo<path>
        string(JSON obj ERROR_VARIABLE noout GET "${json}" ${i} output)
        if(noout OR obj STREQUAL "")
            set(obj "")
            set(take_next OFF)
            foreach(a IN LISTS args)
                if(take_next)
                    set(obj "${a}")
                    break()
                elseif(a STREQUAL "-o")
                    set(take_next ON)
                elseif(a MATCHES "^-o(.+)$" OR a MATCHES "^[/-]Fo(.+)$")
                    set(obj "${CMAKE_MATCH_1}")
                    break()
                endif()
            endforeach()
        endif()
        if(nodir)
            set(dir "")
        endif()
        expand_response_files(args "${dir}" ${args})
        set(in_targets OFF)
        foreach(t IN LISTS targets)
            if(obj MATCHES "(^|[/\\\\])${t}[/\\\\]")
                set(in_targets ON)
            endif()
        endforeach()
        if(EXISTS "${file}")
            file(REAL_PATH "${file}" rfile)
        else()
            set(rfile "${file}")
        endif()
        list(FIND sources "${rfile}" listed)
        get_filename_component(short "${file}" NAME)
        if(listed EQUAL -1)
            if(in_targets)
                list(APPEND violations "${short}: compiled into ${obj}, but not one of the sources this gate holds (${file}) — sources.txt and the target disagree")
            endif()
            continue()
        endif()
        if(NOT obj STREQUAL "" AND NOT in_targets)
            continue()        # the same source compiled by another target
        endif()
        math(EXPR checked "${checked} + 1")
        string(MAKE_C_IDENTIFIER "${rfile}" id)
        math(EXPR checked_${id} "${checked_${id}} + 1")

        # the last appearance of the group, in order
        list(LENGTH args nargs)
        set(group_at -1)
        if(nargs GREATER_EQUAL group_n)
            math(EXPR last_start "${nargs} - ${group_n}")
            foreach(p RANGE ${last_start})
                set(match ON)
                math(EXPR last_g "${group_n} - 1")
                foreach(g RANGE ${last_g})
                    math(EXPR q "${p} + ${g}")
                    list(GET args ${q} a)
                    list(GET group ${g} want)
                    if(NOT a STREQUAL want)
                        set(match OFF)
                        break()
                    endif()
                endforeach()
                if(match)
                    set(group_at ${p})
                endif()
            endforeach()
        endif()
        if(group_at LESS 0)
            list(APPEND violations "${short}: the library's flag group `${group_text}` is not on its compile line, in order — removed, split, or de-duplicated away")
        endif()
        set(pos 0)
        math(EXPR group_end "${group_at} + ${group_n} - 1")
        foreach(a IN LISTS args)
            if(a MATCHES "${UNREADABLE}" OR a MATCHES "^<unreadable response file")
                list(APPEND violations "${short}: `${a}` — a forced include, a pass-through, a plugin, a flag file or an unreadable response file: it carries flags or pragmas this gate cannot read")
            elseif(group_at GREATER_EQUAL 0 AND pos GREATER group_end AND a MATCHES "${FP_SEMANTICS}")
                list(APPEND violations "${short}: `${a}` comes after the library's flag group — it changes floating-point semantics, exceptions or RTTI past the library's own word")
            endif()
            math(EXPR pos "${pos} + 1")
        endforeach()
    endforeach()
endif()
foreach(s IN LISTS sources)
    string(MAKE_C_IDENTIFIER "${s}" id)
    if(checked_${id} EQUAL 0)
        list(APPEND violations "${s}: no compile command in ${COMPILE_COMMANDS} builds it into ${TARGETS} — a source this gate holds, and nothing it read")
    endif()
endforeach()
if(violations)
    string(REPLACE ";" "\n  " report "${violations}")
    message(FATAL_ERROR "felitronics::session compile line (${COMPILE_COMMANDS}):\n  ${report}")
endif()
message(STATUS "felitronics::session compile line: ${checked} compile command(s) for ${TARGETS}, each ending its floating-point, exception and RTTI word with `${group_text}`")
