# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
#
# THE COMPILE LINE OF felitronics::session, READ BACK from compile_commands.json. Run by ctest:
#   cmake -DCOMPILE_COMMANDS=<compile_commands.json> -DTARGET_DIR=felitronics_session.dir -P compile-line-gate.cmake
#
# FP contraction is the one flag no preprocessor macro announces on clang or gcc, so src/BuildGuards.h cannot refuse a
# translation unit compiled with it. What the build ACTUALLY hands the compiler can be read, though, and for every
# source of the library (the entries whose object lives under TARGET_DIR) this requires:
#   * the LAST -ffp-contract= on the line is `off` — so a per-source override, or CMake de-duplicating the library's own
#     `off` away because a parent stated it first (it happened), is red;
#   * nothing after the last -fno-fast-math licenses fast math (-ffast-math, -Ofast, -funsafe-math-optimizations,
#     -fassociative-math, -freciprocal-math, -fno-signed-zeros, -ffinite-math-only);
#   * the last word on exceptions and on RTTI is -fno-exceptions and -fno-rtti.
cmake_minimum_required(VERSION 3.22)
foreach(var COMPILE_COMMANDS TARGET_DIR)
    if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
        message(FATAL_ERROR "compile-line-gate.cmake: ${var} is not set")
    endif()
endforeach()
if(NOT EXISTS "${COMPILE_COMMANDS}")
    message(FATAL_ERROR "compile-line-gate.cmake: ${COMPILE_COMMANDS} does not exist")
endif()
file(READ "${COMPILE_COMMANDS}" json)
string(JSON n LENGTH "${json}")
set(checked 0)
set(violations "")
if(n GREATER 0)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON out ERROR_VARIABLE noout GET "${json}" ${i} output)
        string(JSON file GET "${json}" ${i} file)
        if(noout OR NOT out MATCHES "(^|[/\\\\])${TARGET_DIR}[/\\\\]")
            continue()
        endif()
        string(JSON cmd ERROR_VARIABLE nocmd GET "${json}" ${i} command)
        if(nocmd)
            message(FATAL_ERROR "compile-line-gate.cmake: entry for ${file} has no `command`")
        endif()
        separate_arguments(args UNIX_COMMAND "${cmd}")
        math(EXPR checked "${checked} + 1")
        set(contract "")
        set(pos 0)
        set(last_nofast -1)
        set(last_fast -1)
        set(fast_flag "")
        set(exceptions "")
        set(rtti "")
        foreach(a IN LISTS args)
            if(a MATCHES "^-ffp-contract=(.*)$")
                set(contract "${CMAKE_MATCH_1}")
            elseif(a STREQUAL "-fno-fast-math")
                set(last_nofast ${pos})
            elseif(a MATCHES "^(-ffast-math|-Ofast|-funsafe-math-optimizations|-fassociative-math|-freciprocal-math|-fno-signed-zeros|-ffinite-math-only)$")
                set(last_fast ${pos})
                set(fast_flag "${a}")
            elseif(a MATCHES "^-f(no-)?exceptions$")
                set(exceptions "${a}")
            elseif(a MATCHES "^-f(no-)?rtti$")
                set(rtti "${a}")
            endif()
            math(EXPR pos "${pos} + 1")
        endforeach()
        get_filename_component(short "${file}" NAME)
        if(NOT contract STREQUAL "off")
            list(APPEND violations "${short}: the last -ffp-contract= is '${contract}', not 'off'")
        endif()
        if(last_nofast LESS 0 OR last_fast GREATER last_nofast)
            list(APPEND violations "${short}: fast math is licensed after the last -fno-fast-math ('${fast_flag}')")
        endif()
        if(NOT exceptions STREQUAL "-fno-exceptions")
            list(APPEND violations "${short}: the last word on exceptions is '${exceptions}', not -fno-exceptions")
        endif()
        if(NOT rtti STREQUAL "-fno-rtti")
            list(APPEND violations "${short}: the last word on RTTI is '${rtti}', not -fno-rtti")
        endif()
    endforeach()
endif()
if(checked EQUAL 0)
    message(FATAL_ERROR "compile-line-gate.cmake: no compile command in ${COMPILE_COMMANDS} builds an object under ${TARGET_DIR} — a gate over nothing reads as a pass")
endif()
if(violations)
    string(REPLACE ";" "\n  " report "${violations}")
    message(FATAL_ERROR "felitronics::session compile line (${COMPILE_COMMANDS}):\n  ${report}")
endif()
message(STATUS "felitronics::session compile line: ${checked} translation unit(s), each ends -ffp-contract=off, no fast math after -fno-fast-math, -fno-exceptions, -fno-rtti")
