# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
#
# THE OBJECT-FILE GATE of felitronics::session. Run by ctest (tests/SessionTestTools.cmake):
#   cmake -DFORMAT=elf|macho|coff|wasm -DTOOL=<reader> -DOBJECTS_FILE=<role|path lines> -DLISTS=<session-objects.txt>
#         -DSANITIZERS=ON|OFF [-DEXPECT=<re&&&re...>] -P object-gates.cmake
#
# WHY THE OBJECT FILE AND NOT THE SOURCE. The laws "no mutable state outside an object" and "no operating system, file,
# console, locale, clock or process state" are questions about what the compiled code KEEPS and CALLS. The source asks
# them badly — a lexer cannot tell `int counter (int{0});` from a function declaration, sees nothing through a macro or
# an asm label, and cannot know that <string> made printf visible. The object file answers them exactly:
#   WRITABLE  every symbol in a writable section is state with static storage duration. The answer must be empty — the C
#             boundary's objects may keep exactly the globals tools/lint/session-objects.txt names, each found once.
#   CALLED    every undefined symbol is something the code reaches outside itself. It must be defined by another object of
#             the set, or match an `undefined` line of the lists (operator new, memcpy, the stack protector ...).
# What this cannot see: code that is never emitted (an inline function nobody called is in no object), and a facility
# that has no symbol — an atomic, a clock read by an intrinsic or inline assembly, a builtin, a pragma. Those are the
# session-laws lint's (tools/lint/check-session-laws.mjs), which is the other half of the gate.
#
# EXPECT turns a run into a CONTROL: the gate must refuse, and each `&&&`-separated regex must match the name of a symbol
# it refused. A control whose object passed, or failed on something else, is red.
cmake_minimum_required(VERSION 3.22)

foreach(var FORMAT TOOL OBJECTS_FILE LISTS SANITIZERS)
    if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
        message(FATAL_ERROR "object-gates.cmake: ${var} is not set")
    endif()
endforeach()
if(NOT FORMAT MATCHES "^(elf|macho|coff|wasm)$")
    message(FATAL_ERROR "object-gates.cmake: unknown FORMAT '${FORMAT}'")
endif()

# ---- the lists ------------------------------------------------------------------------------------------------------
file(STRINGS "${LISTS}" list_lines REGEX "^[a-z]")
set(globals "")          # names allowed to the facade
set(undef_all "")        # patterns, every object
set(undef_facade "")     # patterns, facade objects only
set(writable_all "")     # patterns
foreach(l IN LISTS list_lines)
    if(NOT l MATCHES "^(global|writable|undefined)[ \t]+([a-z-]+)[ \t]+([^ \t]+)[ \t]+[^ \t]")
        message(FATAL_ERROR "object-gates.cmake: ${LISTS}: unreadable line: ${l}")
    endif()
    set(kind "${CMAKE_MATCH_1}")
    set(scope "${CMAKE_MATCH_2}")
    set(pat "${CMAKE_MATCH_3}")
    set(applies OFF)
    set(facade_only OFF)
    if(scope STREQUAL "all" OR scope STREQUAL FORMAT)
        set(applies ON)
    elseif(scope STREQUAL "san")
        set(applies ${SANITIZERS})
    elseif(scope STREQUAL "facade" OR scope STREQUAL "facade-${FORMAT}")
        set(applies ON)
        set(facade_only ON)
    elseif(NOT scope MATCHES "^(elf|macho|coff|wasm|facade-(elf|macho|coff|wasm))$")
        message(FATAL_ERROR "object-gates.cmake: ${LISTS}: unknown scope '${scope}' in: ${l}")
    endif()
    if(NOT applies)
        continue()
    endif()
    if(kind STREQUAL "global")
        if(NOT facade_only)
            message(FATAL_ERROR "object-gates.cmake: ${LISTS}: a `global` allowance is for the facade only: ${l}")
        endif()
        list(APPEND globals "${pat}")
    elseif(kind STREQUAL "writable")
        list(APPEND writable_all "${pat}")
    elseif(facade_only)
        list(APPEND undef_facade "${pat}")
    else()
        list(APPEND undef_all "${pat}")
    endif()
endforeach()

# ---- reading one object -----------------------------------------------------------------------------------------------
# A tool's output as a CMake list of lines. `;` is escaped, and `[` / `]` are replaced by <lb> / <rb> for the whole of the
# run: CMake's list splitting does not split inside square brackets, so a line like `Symbols [` merged every line up to
# the next `]` into one element (llvm-readobj's whole symbol table read as one line, and the gate saw nothing). Names keep
# the placeholders until the report prints them.
function(split_lines text out)
    string(REPLACE ";" "\\;" text "${text}")
    string(REPLACE "[" "<lb>" text "${text}")
    string(REPLACE "]" "<rb>" text "${text}")
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE "\n" ";" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

# Fills, in the caller's scope: o_undef (raw names), o_undef_dem, o_writable (raw), o_writable_dem, o_writable_sec,
# o_defined (raw names).
function(read_object obj)
    set(u "")
    set(ud "")
    set(w "")
    set(wd "")
    set(ws "")
    set(d "")
    if(FORMAT STREQUAL "elf" OR FORMAT STREQUAL "macho")
        execute_process(COMMAND "${TOOL}" -t "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        execute_process(COMMAND "${TOOL}" -t -C "${obj}" RESULT_VARIABLE rc2 OUTPUT_VARIABLE dem ERROR_VARIABLE err2)
        if(NOT rc EQUAL 0 OR NOT rc2 EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} -t ${obj} failed: ${err}${err2}")
        endif()
        split_lines("${raw}" raw_lines)
        split_lines("${dem}" dem_lines)
        list(LENGTH raw_lines n)
        list(LENGTH dem_lines n2)
        if(NOT n EQUAL n2)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} gave ${n} lines mangled and ${n2} demangled for ${obj}")
        endif()
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            list(GET raw_lines ${i} line)
            list(GET dem_lines ${i} dline)
            if(NOT line MATCHES "^([0-9a-fA-F]+) (.......) ([^ \t]+)[ \t]+(.*)$")
                continue()
            endif()
            set(flags "${CMAKE_MATCH_2}")
            set(sec "${CMAKE_MATCH_3}")
            set(name "${CMAKE_MATCH_4}")
            dline_name("${dline}" dname)
            string(SUBSTRING "${flags}" 5 1 dflag)
            if(dflag STREQUAL "d")             # a section or debugging symbol, or the file name
                continue()
            endif()
            # (string(REGEX MATCH), never REGEX REPLACE with `^`: CMake re-applies an anchored REPLACE at the start of
            # what remains, so `^_` strips EVERY leading underscore and `__Znwm` became `Znwm`.)
            if(FORMAT STREQUAL "elf" AND name MATCHES "^[0-9a-fA-F]+[ \t]+(.*)$")
                set(name "${CMAKE_MATCH_1}")     # the size column ELF prints before the name
            endif()
            if(name MATCHES "^\\.(hidden|protected|internal) (.*)$")
                set(name "${CMAKE_MATCH_2}")
            endif()
            if(FORMAT STREQUAL "elf" AND name MATCHES "^\\.L")
                continue()                       # an assembler-local label
            endif()
            if(FORMAT STREQUAL "macho")
                if(name MATCHES "^(ltmp[0-9]+$|l_|L_|lCPI|LCPI|Ltmp|LBB)")
                    continue()                   # an assembler-local label (ltmp0, l_.str, LCPI0_0)
                endif()
                if(name MATCHES "^_(.*)$")
                    set(name "${CMAKE_MATCH_1}") # Mach-O's one leading underscore
                endif()
            endif()
            if(sec STREQUAL "*UND*")
                list(APPEND u "${name}")
                list(APPEND ud "${dname}")
            else()
                list(APPEND d "${name}")
                set(writable OFF)
                if(FORMAT STREQUAL "elf")
                    if((sec MATCHES "^\\.(data|bss|tdata|tbss|sdata|sbss)(\\.|$)" AND NOT sec MATCHES "^\\.data\\.rel\\.ro")
                       OR sec STREQUAL "*COM*")
                        set(writable ON)
                    endif()
                elseif(sec MATCHES "^__DATA,__(data|bss|common|thread_data|thread_bss|thread_vars)$")
                    set(writable ON)
                endif()
                if(writable)
                    list(APPEND w "${name}")
                    list(APPEND wd "${dname}")
                    list(APPEND ws "${sec}")
                endif()
            endif()
        endforeach()
    elseif(FORMAT STREQUAL "coff")
        execute_process(COMMAND "${TOOL}" /nologo /symbols "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} /symbols ${obj} failed: ${err}")
        endif()
        split_lines("${raw}" lines)
        set(sections "")
        foreach(pass 1 2)
            foreach(line IN LISTS lines)
                if(NOT line MATCHES "^[0-9A-F]+ [0-9A-F]+ ([A-Z0-9]+) +[a-z]+( \\(\\))? +([A-Za-z]+) +\\| (.*)$")
                    continue()
                endif()
                set(secno "${CMAKE_MATCH_1}")
                set(storage "${CMAKE_MATCH_3}")
                set(rest "${CMAKE_MATCH_4}")
                string(REGEX MATCH "^[^ ]+" name "${rest}")
                set(dname "${name}")
                if(rest MATCHES "^[^ ]+ \\((.*)\\)$")
                    set(dname "${CMAKE_MATCH_1}")
                endif()
                if(pass EQUAL 1)
                    if(storage STREQUAL "Static" AND name MATCHES "^\\." AND secno MATCHES "^SECT")
                        set(sec_${secno} "${name}")
                    endif()
                    continue()
                endif()
                if(storage STREQUAL "Label" OR secno STREQUAL "ABS" OR secno STREQUAL "DEBUG")
                    continue()
                endif()
                if(storage STREQUAL "Static" AND name MATCHES "^\\.")
                    continue()                   # the section symbol itself
                endif()
                if(secno STREQUAL "UNDEF")
                    if(storage STREQUAL "External")
                        list(APPEND u "${name}")
                        list(APPEND ud "${dname}")
                    endif()
                    continue()
                endif()
                list(APPEND d "${name}")
                if(DEFINED sec_${secno} AND sec_${secno} MATCHES "^\\.(data|bss|tls)($|\\$)")
                    list(APPEND w "${name}")
                    list(APPEND wd "${dname}")
                    list(APPEND ws "${sec_${secno}}")
                endif()
            endforeach()
        endforeach()
    else() # wasm
        execute_process(COMMAND "${TOOL}" --sections --symbols "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        execute_process(COMMAND "${TOOL}" --sections --symbols --demangle "${obj}" RESULT_VARIABLE rc2 OUTPUT_VARIABLE dem ERROR_VARIABLE err2)
        if(NOT rc EQUAL 0 OR NOT rc2 EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} ${obj} failed: ${err}${err2}")
        endif()
        split_lines("${raw}" raw_lines)
        split_lines("${dem}" dem_lines)
        list(LENGTH raw_lines n)
        list(LENGTH dem_lines n2)
        if(NOT n EQUAL n2)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} gave ${n} lines mangled and ${n2} demangled for ${obj}")
        endif()
        set(segs "")
        set(in_segs OFF)
        set(in_syms OFF)
        set(in_sym OFF)
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            list(GET raw_lines ${i} line)
            list(GET dem_lines ${i} dline)
            if(line MATCHES "^ *Segments <lb>")
                set(in_segs ON)
                continue()
            endif()
            if(in_segs)
                if(line MATCHES "^ *<rb>$")
                    set(in_segs OFF)
                elseif(line MATCHES "^ *Name: (.*)$")
                    list(APPEND segs "${CMAKE_MATCH_1}")
                endif()
                continue()
            endif()
            if(line MATCHES "^Symbols <lb>")
                set(in_syms ON)
                continue()
            endif()
            if(NOT in_syms)
                continue()
            endif()
            if(line MATCHES "^  Symbol \\{")
                set(in_sym ON)
                set(s_name "")
                set(s_dname "")
                set(s_undef OFF)
                set(s_seg "")
                continue()
            endif()
            if(in_sym AND line MATCHES "^  \\}")
                set(in_sym OFF)
                if(s_name MATCHES "^\\.L")
                    continue()
                endif()
                if(s_undef)
                    list(APPEND u "${s_name}")
                    list(APPEND ud "${s_dname}")
                else()
                    list(APPEND d "${s_name}")
                    if(NOT s_seg STREQUAL "")
                        math(EXPR idx "0x${s_seg}" OUTPUT_FORMAT DECIMAL)
                        list(LENGTH segs nsegs)
                        if(idx LESS nsegs)
                            list(GET segs ${idx} segname)
                            if(segname MATCHES "^\\.(data|bss|tdata|tbss)(\\.|$)")
                                list(APPEND w "${s_name}")
                                list(APPEND wd "${s_dname}")
                                list(APPEND ws "${segname}")
                            endif()
                        else()
                            message(FATAL_ERROR "object-gates.cmake: ${obj}: symbol ${s_name} names segment ${idx} of ${nsegs}")
                        endif()
                    endif()
                endif()
                continue()
            endif()
            if(in_sym)
                if(s_name STREQUAL "" AND line MATCHES "^    Name: (.*)$")
                    set(s_name "${CMAKE_MATCH_1}")
                    if(dline MATCHES "^    Name: (.*)$")
                        set(s_dname "${CMAKE_MATCH_1}")
                    endif()
                elseif(line MATCHES "UNDEFINED \\(")
                    set(s_undef ON)
                elseif(line MATCHES "^    Segment: 0x([0-9A-Fa-f]+)$")
                    set(s_seg "${CMAKE_MATCH_1}")
                endif()
            endif()
        endforeach()
    endif()
    foreach(v u ud w wd ws d)
        set(o_${v} "${${v}}" PARENT_SCOPE)
    endforeach()
endfunction()

# The demangled line's name field, taken the same way as the mangled one.
function(dline_name dline out)
    set(n "")
    if(dline MATCHES "^[0-9a-fA-F]+ ....... [^ \t]+[ \t]+(.*)$")
        set(n "${CMAKE_MATCH_1}")
        if(FORMAT STREQUAL "elf" AND n MATCHES "^[0-9a-fA-F]+[ \t]+(.*)$")
            set(n "${CMAKE_MATCH_1}")
        endif()
        if(n MATCHES "^\\.(hidden|protected|internal) (.*)$")
            set(n "${CMAKE_MATCH_2}")
        endif()
    endif()
    set(${out} "${n}" PARENT_SCOPE)
endfunction()

# ---- all objects -----------------------------------------------------------------------------------------------------
file(STRINGS "${OBJECTS_FILE}" entries REGEX "^(library|facade)\\|")
if(NOT entries)
    message(FATAL_ERROR "object-gates.cmake: ${OBJECTS_FILE} names no object — a gate over nothing reads as a pass")
endif()
set(all_defined "")
set(n_objects 0)
foreach(e IN LISTS entries)
    string(REGEX MATCH "^([a-z]+)\\|(.*)$" _ "${e}")
    set(role "${CMAKE_MATCH_1}")
    set(obj "${CMAKE_MATCH_2}")
    if(NOT EXISTS "${obj}")
        message(FATAL_ERROR "object-gates.cmake: ${obj} does not exist — build before testing")
    endif()
    math(EXPR n_objects "${n_objects} + 1")
    read_object("${obj}")
    list(APPEND all_defined ${o_d})
    set(obj_${n_objects}_role "${role}")
    set(obj_${n_objects}_path "${obj}")
    foreach(v u ud w wd ws)
        set(obj_${n_objects}_${v} "${o_${v}}")
    endforeach()
endforeach()

set(violations "")
set(violating_names "")
set(n_writable 0)
set(n_undef 0)
foreach(g IN LISTS globals)
    set(found_${g} 0)
endforeach()
foreach(k RANGE 1 ${n_objects})
    set(role "${obj_${k}_role}")
    get_filename_component(short "${obj_${k}_path}" NAME)
    # WRITABLE
    list(LENGTH obj_${k}_w nw)
    if(nw GREATER 0)
        math(EXPR lastw "${nw} - 1")
        foreach(i RANGE ${lastw})
            list(GET obj_${k}_w ${i} name)
            list(GET obj_${k}_wd ${i} dname)
            list(GET obj_${k}_ws ${i} sec)
            math(EXPR n_writable "${n_writable} + 1")
            set(ok OFF)
            if(role STREQUAL "facade")
                foreach(g IN LISTS globals)
                    # by the demangled name, or — where the reader does not demangle (llvm-readobj on wasm) — by the
                    # Itanium name's own length prefix, so `7g_slots` matches g_slots and not g_slotsExtra
                    string(LENGTH "${g}" glen)
                    if(dname MATCHES "(^|[:' ])${g}($|[^A-Za-z0-9_])" OR name MATCHES "${glen}${g}(E|$)")
                        math(EXPR found_${g} "${found_${g}} + 1")
                        set(ok ON)
                    endif()
                endforeach()
            endif()
            foreach(p IN LISTS writable_all)
                if(name MATCHES "${p}")
                    set(ok ON)
                endif()
            endforeach()
            if(NOT ok)
                list(APPEND violations "[WRITABLE] ${short}: `${dname}` (${name}) lives in ${sec} — state with static storage duration that the code can change")
                list(APPEND violating_names "${name} ${dname}")
            endif()
        endforeach()
    endif()
    # CALLED
    list(LENGTH obj_${k}_u nu)
    if(nu GREATER 0)
        math(EXPR lastu "${nu} - 1")
        foreach(i RANGE ${lastu})
            list(GET obj_${k}_u ${i} name)
            list(GET obj_${k}_ud ${i} dname)
            math(EXPR n_undef "${n_undef} + 1")
            list(FIND all_defined "${name}" defined_here)
            if(NOT defined_here EQUAL -1)
                continue()
            endif()
            set(ok OFF)
            foreach(p IN LISTS undef_all)
                if(name MATCHES "${p}")
                    set(ok ON)
                endif()
            endforeach()
            if(role STREQUAL "facade")
                foreach(p IN LISTS undef_facade)
                    if(name MATCHES "${p}")
                        set(ok ON)
                    endif()
                endforeach()
            endif()
            if(NOT ok)
                list(APPEND violations "[CALLED] ${short}: `${dname}` (${name}) — reached outside the library and not on the list in tools/lint/session-objects.txt")
                list(APPEND violating_names "${name} ${dname}")
            endif()
        endforeach()
    endif()
endforeach()

# Each allowance names something that is there, exactly once — when there is a facade object to find it in.
set(have_facade OFF)
foreach(k RANGE 1 ${n_objects})
    if(obj_${k}_role STREQUAL "facade")
        set(have_facade ON)
    endif()
endforeach()
if(have_facade)
    foreach(g IN LISTS globals)
        if(NOT found_${g} EQUAL 1)
            list(APPEND violations "[ALLOWANCE] the facade's global `${g}` was found ${found_${g}} time(s) in its objects — an allowance must name exactly one symbol that is there")
            list(APPEND violating_names "${g}")
        endif()
    endforeach()
endif()

string(REPLACE ";" "\n  " report "${violations}")
string(REPLACE "<lb>" "[" report "${report}")
string(REPLACE "<rb>" "]" report "${report}")
set(summary "${n_objects} object(s), ${n_writable} writable symbol(s), ${n_undef} called symbol(s) read with ${TOOL} (${FORMAT})")
if(DEFINED EXPECT AND NOT EXPECT STREQUAL "")
    if(NOT violations)
        message(FATAL_ERROR "CONTROL FAILED: the gate PASSED a planted violation — ${summary}")
    endif()
    string(REPLACE "&&&" ";" expects "${EXPECT}")
    foreach(re IN LISTS expects)
        set(hit OFF)
        foreach(v IN LISTS violating_names)
            if(v MATCHES "${re}")
                set(hit ON)
            endif()
        endforeach()
        if(NOT hit)
            message(FATAL_ERROR "CONTROL FAILED: the gate refused, but named nothing matching /${re}/:\n  ${report}")
        endif()
    endforeach()
    message(STATUS "control ok: the gate refuses the plant — ${summary}:\n  ${report}")
    return()
endif()
if(violations)
    message(FATAL_ERROR "felitronics::session object-file gate: ${summary}:\n  ${report}")
endif()
message(STATUS "felitronics::session object-file gate: clean — ${summary}")
