# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko & Alisa Lafoks. Part of felitronics-mastering-core — see LICENSE.
#
# THE OBJECT-FILE GATE of felitronics::session. Run by ctest (tests/SessionTestTools.cmake):
#   cmake -DFORMAT=elf|macho|coff|wasm -DTOOL=<reader> -DOBJECTS_FILE=<role|path lines> -DLISTS=<session-objects.txt>
#         -DSANITIZERS=ON|OFF -DMSVC_DEBUG=ON|OFF [-DEXPECT=<re&&&re...>] -P object-gates.cmake
# MSVC_DEBUG is ON for an MSVC build in its Debug configuration (/MDd): the lists' `coff-debug` lines apply then alone.
#
# WHY THE OBJECT FILE AND NOT THE SOURCE. The laws "no mutable state outside an object" and "no operating system, file,
# console, locale, clock or process state" are questions about what the compiled code KEEPS and CALLS. The source asks
# them badly — a lexer cannot tell `int counter (int{0});` from a function declaration, sees nothing through a macro or
# an asm label, and cannot know that <string> made printf visible. The object file answers them exactly:
#   WRITABLE  every symbol in a writable section is state with static storage duration. The answer must be empty — the C
#             boundary's objects may keep exactly the globals tools/lint/session-objects.txt names, each found once.
#             Writable is what the object says of the section (its write flag, or — where the format has none — every
#             place not on the short list of read-only ones), never a list of writable NAMES: a section attribute
#             chooses any name it likes (tests/object-controls/custom_section.cpp).
#             RELOCATED CONSTANT DATA IS NOT WRITABLE STATE and is not refused: ELF .data.rel.ro / .data.rel.ro.local,
#             Mach-O __DATA,__const and __DATA_CONST, COFF .rdata, wasm .rodata and .data.rel.ro — a constexpr table of
#             pointers lives there, written by the loader and never by the code (tests/object-controls/
#             constexpr_pointer_table.cpp must pass). ELF marks .data.rel.ro writable (the loader writes it before RELRO
#             protects it), so there the NAME is trusted — and the session-laws lint refuses every section attribute,
#             so session code cannot choose that name.
#   CALLED    every undefined symbol is something the code reaches outside itself. It must be defined — with global or
#             weak binding — by another object of the set, or match an `undefined` line of the lists (operator new,
#             memcpy, the stack protector ...). A LOCAL definition answers no other object's call
#             (tests/object-controls/local_definition_*.cpp).
# What this cannot see: code that is never emitted (an inline function nobody called is in no object), and a facility
# that has no symbol — an atomic, a clock read by an intrinsic or inline assembly, a builtin, a pragma. Those are the
# session-laws lint's (tools/lint/check-session-laws.mjs), which is the other half of the gate.
#
# EXPECT turns a run into a CONTROL: the gate must refuse, and each `&&&`-separated regex must match, in full, a name of a
# symbol it refused (see name_candidates). A control whose object passed, or failed on something else, is red.
cmake_minimum_required(VERSION 3.22)

foreach(var FORMAT TOOL OBJECTS_FILE LISTS SANITIZERS MSVC_DEBUG)
    if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
        message(FATAL_ERROR "object-gates.cmake: ${var} is not set")
    endif()
endforeach()
if(NOT FORMAT MATCHES "^(elf|macho|coff|wasm)$")
    message(FATAL_ERROR "object-gates.cmake: unknown FORMAT '${FORMAT}'")
endif()

# ---- the lists ------------------------------------------------------------------------------------------------------
file(STRINGS "${LISTS}" list_lines REGEX "^[a-z]")
set(globals "")          # names allowed to the facade
set(undef_all "")        # patterns, every object
set(undef_facade "")     # patterns, facade objects only
set(writable_all "")     # patterns
foreach(l IN LISTS list_lines)
    if(NOT l MATCHES "^(global|writable|undefined)[ \t]+([a-z-]+)[ \t]+([^ \t]+)[ \t]+[^ \t]")
        message(FATAL_ERROR "object-gates.cmake: ${LISTS}: unreadable line: ${l}")
    endif()
    set(kind "${CMAKE_MATCH_1}")
    set(scope "${CMAKE_MATCH_2}")
    set(pat "${CMAKE_MATCH_3}")
    set(applies OFF)
    set(facade_only OFF)
    if(scope STREQUAL "all" OR scope STREQUAL FORMAT)
        set(applies ON)
    elseif(scope STREQUAL "san")
        set(applies ${SANITIZERS})
    elseif(scope STREQUAL "coff-debug")
        if(FORMAT STREQUAL "coff" AND MSVC_DEBUG)
            set(applies ON)
        endif()
    elseif(scope STREQUAL "facade" OR scope STREQUAL "facade-${FORMAT}")
        set(applies ON)
        set(facade_only ON)
    elseif(NOT scope MATCHES "^(elf|macho|coff|wasm|facade-(elf|macho|coff|wasm))$")
        message(FATAL_ERROR "object-gates.cmake: ${LISTS}: unknown scope '${scope}' in: ${l}")
    endif()
    if(NOT applies)
        continue()
    endif()
    if(kind STREQUAL "global")
        if(NOT facade_only)
            message(FATAL_ERROR "object-gates.cmake: ${LISTS}: a `global` allowance is for the facade only: ${l}")
        endif()
        list(APPEND globals "${pat}")
    elseif(kind STREQUAL "writable")
        list(APPEND writable_all "${pat}")
    elseif(facade_only)
        list(APPEND undef_facade "${pat}")
    else()
        list(APPEND undef_all "${pat}")
    endif()
endforeach()

# ---- reading one object -----------------------------------------------------------------------------------------------
# A tool's output as a CMake list of lines. `;` is escaped, and `[` / `]` are replaced by <lb> / <rb> for the whole of the
# run: CMake's list splitting does not split inside square brackets, so a line like `Symbols [` merged every line up to
# the next `]` into one element (llvm-readobj's whole symbol table read as one line, and the gate saw nothing). Names keep
# the placeholders until the report prints them.
function(split_lines text out)
    string(REPLACE ";" "\;" text "${text}")
    string(REPLACE "[" "<lb>" text "${text}")
    string(REPLACE "]" "<rb>" text "${text}")
    string(REPLACE "\r" "" text "${text}")
    string(REPLACE "\n" ";" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

# WHICH MEMORY IS WRITABLE, decided by what the object SAYS about its sections — never by a list of writable names, which a
# section attribute walks straight past (`[[gnu::section("__DATA,__session")]] int n;` passed a name list on Mach-O and
# on wasm). Relocated constant data — a constexpr table of pointers — is written by the loader, never by the code, and
# is read-only here on every format.
#   ELF     the section's flags (readelf): writable iff ALLOCated and WRITE, except .data.rel.ro* (relocated constants,
#           read-only after relocation), and COMMON.
#   Mach-O  no write flag per section, so the READ-ONLY places are the allowlist: segment __TEXT, segment __DATA_CONST,
#           and __DATA,__const. Every other section of a data symbol is writable.
#   COFF    the section's characteristics (dumpbin /headers): IMAGE_SCN_MEM_WRITE, 0x80000000.
#   wasm    read-only segments are the allowlist: .rodata* and .data.rel.ro*. Every other data segment is writable.
#
# AND WHICH DEFINITIONS CAN ANSWER A CALL: a LOCAL definition (static, anonymous namespace, a C function declared static)
# never resolves another object's undefined reference — the linker takes that reference outside. So only a symbol with
# global or weak binding enters the set that resolves calls; a local `getpid` in one object leaves another object's
# `getpid` call exactly as undefined as it was.
#
# Fills, in the caller's scope: o_u / o_ud (undefined raw / demangled), o_w / o_wd / o_ws (writable raw / demangled /
# section), o_d (raw names of GLOBAL or WEAK definitions).
function(read_object obj)
    set(u "")
    set(ud "")
    set(w "")
    set(wd "")
    set(ws "")
    set(d "")
    if(FORMAT STREQUAL "elf")
        execute_process(COMMAND "${TOOL}" -S -W "${obj}" RESULT_VARIABLE rc1 OUTPUT_VARIABLE secs ERROR_VARIABLE e1)
        execute_process(COMMAND "${TOOL}" -s -W "${obj}" RESULT_VARIABLE rc2 OUTPUT_VARIABLE raw ERROR_VARIABLE e2)
        execute_process(COMMAND "${TOOL}" -s -W -C "${obj}" RESULT_VARIABLE rc3 OUTPUT_VARIABLE dem ERROR_VARIABLE e3)
        if(NOT rc1 EQUAL 0 OR NOT rc2 EQUAL 0 OR NOT rc3 EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} ${obj} failed: ${e1}${e2}${e3}")
        endif()
        split_lines("${secs}" sec_lines)
        foreach(line IN LISTS sec_lines)
            # `  [ 4] .bss   NOBITS   0000000000000000 0000b4 000004 00  WA  0   0  4` — the flags may be empty
            if(line MATCHES "^ *<lb> *([0-9]+)<rb> +([^ ]+) +[^ ]+ +[0-9a-fA-F]+ +[0-9a-fA-F]+ +[0-9a-fA-F]+ +[0-9a-fA-F]+ +([A-Za-z]*) +[0-9]+ +[0-9]+ +[0-9]+ *$")
                set(secname_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
                set(secflags_${CMAKE_MATCH_1} "${CMAKE_MATCH_3}")
            endif()
        endforeach()
        split_lines("${raw}" raw_lines)
        split_lines("${dem}" dem_lines)
        list(LENGTH raw_lines n)
        list(LENGTH dem_lines n2)
        if(NOT n EQUAL n2)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} gave ${n} lines mangled and ${n2} demangled for ${obj}")
        endif()
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            list(GET raw_lines ${i} line)
            list(GET dem_lines ${i} dline)
            #   `    12: 0000000000000000     4 OBJECT  GLOBAL DEFAULT   11 sectionCounter` — the visibility may carry a
            #   bracketed note (`DEFAULT [VARIANT_PCS]` on aarch64). An entry line that does not parse is an error, never
            #   a symbol skipped: the one entry without a name is the null symbol at index 0.
            if(NOT line MATCHES "^ *[0-9]+: ")
                continue()
            endif()
            set(entry_re "^ *[0-9]+: +[0-9a-fA-F]+ +[0-9xa-fA-F]+ +([A-Z_]+) +([A-Z_]+) +[A-Z_]+( +<lb>[^<]*<rb>)? +([A-Z0-9]+)( +(.*[^ ]))? *$")
            if(NOT line MATCHES "${entry_re}")
                message(FATAL_ERROR "object-gates.cmake: ${obj}: unreadable symbol entry from ${TOOL} -s -W: ${line}")
            endif()
            set(type "${CMAKE_MATCH_1}")
            set(bind "${CMAKE_MATCH_2}")
            set(ndx "${CMAKE_MATCH_4}")
            set(name "${CMAKE_MATCH_6}")
            if(name STREQUAL "")
                continue()
            endif()
            set(dname "${name}")
            if(dline MATCHES "${entry_re}" AND NOT CMAKE_MATCH_6 STREQUAL "")
                set(dname "${CMAKE_MATCH_6}")
            endif()
            if(type STREQUAL "SECTION" OR type STREQUAL "FILE" OR ndx STREQUAL "ABS" OR name MATCHES "^\\.L")
                continue()
            endif()
            # A mapping symbol ($d, $x, $d.1 — where data and code begin in a section, on AArch64, ARM and RISC-V) names
            # a position, not an object: local, untyped, and in every section that has data.
            if(type STREQUAL "NOTYPE" AND bind STREQUAL "LOCAL" AND name MATCHES "^\\$[a-z](\\..*)?$")
                continue()
            endif()
            if(ndx STREQUAL "UND")
                list(APPEND u "${name}")
                list(APPEND ud "${dname}")
                continue()
            endif()
            if(NOT bind STREQUAL "LOCAL")
                list(APPEND d "${name}")
            endif()
            set(writable OFF)
            set(where "${ndx}")
            if(ndx STREQUAL "COM")
                set(writable ON)
                set(where "COMMON")
            elseif(DEFINED secflags_${ndx})
                set(where "${secname_${ndx}}")
                if(secflags_${ndx} MATCHES "W" AND secflags_${ndx} MATCHES "A"
                   AND NOT secname_${ndx} MATCHES "^\\.data\\.rel\\.ro(\\.|$)")
                    set(writable ON)
                endif()
            else()
                message(FATAL_ERROR "object-gates.cmake: ${obj}: symbol ${name} is in section ${ndx}, which ${TOOL} -S did not list")
            endif()
            if(writable)
                list(APPEND w "${name}")
                list(APPEND wd "${dname}")
                list(APPEND ws "${where}")
            endif()
        endforeach()
    elseif(FORMAT STREQUAL "macho")
        execute_process(COMMAND "${TOOL}" -t "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        execute_process(COMMAND "${TOOL}" -t -C "${obj}" RESULT_VARIABLE rc2 OUTPUT_VARIABLE dem ERROR_VARIABLE err2)
        if(NOT rc EQUAL 0 OR NOT rc2 EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} -t ${obj} failed: ${err}${err2}")
        endif()
        split_lines("${raw}" raw_lines)
        split_lines("${dem}" dem_lines)
        list(LENGTH raw_lines n)
        list(LENGTH dem_lines n2)
        if(NOT n EQUAL n2)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} gave ${n} lines mangled and ${n2} demangled for ${obj}")
        endif()
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            list(GET raw_lines ${i} line)
            list(GET dem_lines ${i} dline)
            # `0000000000000170 l     O __DATA,__bss __ZN12_GLOBAL__N_17counterE`
            if(NOT line MATCHES "^[0-9a-fA-F]+ (.......) ([^ \t]+)[ \t]+(.*)$")
                continue()
            endif()
            set(flags "${CMAKE_MATCH_1}")
            set(sec "${CMAKE_MATCH_2}")
            set(name "${CMAKE_MATCH_3}")
            set(dname "${name}")
            if(dline MATCHES "^[0-9a-fA-F]+ ....... [^ \t]+[ \t]+(.*)$")
                set(dname "${CMAKE_MATCH_1}")
            endif()
            string(SUBSTRING "${flags}" 5 1 dflag)
            if(dflag STREQUAL "d")               # a section or debugging symbol, or the file name
                continue()
            endif()
            # (string(REGEX MATCH), never REGEX REPLACE with `^`: CMake re-applies an anchored REPLACE at the start of what
            # remains, so `^_` stripped EVERY leading underscore.)
            if(name MATCHES "^(ltmp[0-9]+$|l_|L_|lCPI|LCPI|Ltmp|LBB)")
                continue()                       # an assembler-local label (ltmp0, l_.str, LCPI0_0)
            endif()
            if(name MATCHES "^_(.*)$")
                set(name "${CMAKE_MATCH_1}")     # Mach-O's one leading underscore
                if(dname STREQUAL "_${name}")
                    set(dname "${name}")         # a C name, which the demangler hands back as it found it
                endif()
            endif()
            if(sec STREQUAL "*UND*")
                list(APPEND u "${name}")
                list(APPEND ud "${dname}")
                continue()
            endif()
            if(sec STREQUAL "*ABS*")
                continue()
            endif()
            string(SUBSTRING "${flags}" 0 1 binding)
            if(NOT binding STREQUAL "l")
                list(APPEND d "${name}")
            endif()
            if(NOT sec MATCHES "^(__TEXT,|__DATA_CONST,|__DATA,__const$|__LD,)")
                list(APPEND w "${name}")
                list(APPEND wd "${dname}")
                list(APPEND ws "${sec}")
            endif()
        endforeach()
    elseif(FORMAT STREQUAL "coff")
        execute_process(COMMAND "${TOOL}" /nologo /headers /symbols "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} /headers /symbols ${obj} failed: ${err}")
        endif()
        split_lines("${raw}" lines)
        # Section headers: `SECTION HEADER #3`, then the name right-aligned in eight columns (`    .bss name`, and an
        # eight-letter `fcsstate name` with no indent at all), ..., then `C0300080 flags`. The header number is in hex,
        # as the SECTn of the symbol table is.
        set(cur "")
        foreach(line IN LISTS lines)
            if(line MATCHES "^SECTION HEADER #([0-9A-Fa-f]+)")
                string(TOUPPER "${CMAKE_MATCH_1}" cur)
            elseif(NOT cur STREQUAL "" AND line MATCHES "^ *(.*[^ ]) name$")
                set(secname_${cur} "${CMAKE_MATCH_1}")
            elseif(NOT cur STREQUAL "" AND line MATCHES "^ *([0-9A-Fa-f]+) flags$")
                math(EXPR bits "0x${CMAKE_MATCH_1} & 0x80000000" OUTPUT_FORMAT DECIMAL)
                set(secwrite_${cur} ${bits})
                set(cur "")
            endif()
        endforeach()
        foreach(line IN LISTS lines)
            if(NOT line MATCHES "^[0-9A-F]+ [0-9A-F]+ ([A-Z0-9]+) +[a-z]+( \\(\\))? +([A-Za-z]+) +\\| (.*)$")
                continue()
            endif()
            set(secno "${CMAKE_MATCH_1}")
            set(storage "${CMAKE_MATCH_3}")
            set(rest "${CMAKE_MATCH_4}")
            string(REGEX MATCH "^[^ ]+" name "${rest}")
            set(dname "${name}")
            if(rest MATCHES "^[^ ]+ \\((.*)\\)$")
                set(dname "${CMAKE_MATCH_1}")
            endif()
            if(storage STREQUAL "Label" OR secno STREQUAL "ABS" OR secno STREQUAL "DEBUG")
                continue()
            endif()
            if(storage STREQUAL "Static" AND name MATCHES "^\\.")
                continue()                       # the section symbol itself
            endif()
            if(secno STREQUAL "UNDEF")
                if(storage STREQUAL "External")
                    list(APPEND u "${name}")
                    list(APPEND ud "${dname}")
                endif()
                continue()
            endif()
            if(storage STREQUAL "External")
                list(APPEND d "${name}")
            endif()
            if(NOT secno MATCHES "^SECT([0-9A-F]+)$")
                continue()
            endif()
            set(hdr "${CMAKE_MATCH_1}")
            if(NOT DEFINED secwrite_${hdr})
                message(FATAL_ERROR "object-gates.cmake: ${obj}: symbol ${name} is in section ${hdr}, which /headers did not list")
            endif()
            if(NOT secwrite_${hdr} EQUAL 0)
                if(NOT DEFINED secname_${hdr})
                    message(FATAL_ERROR "object-gates.cmake: ${obj}: section ${hdr} has flags but no name that /headers printed")
                endif()
                list(APPEND w "${name}")
                list(APPEND wd "${dname}")
                list(APPEND ws "${secname_${hdr}}")
            endif()
        endforeach()
    else() # wasm
        # llvm-readobj's --demangle does not demangle a wasm object's names, so the SDK's llvm-cxxfilt, beside it, does —
        # once per object, every name on its own line.
        execute_process(COMMAND "${TOOL}" --sections --symbols "${obj}" RESULT_VARIABLE rc OUTPUT_VARIABLE raw ERROR_VARIABLE err)
        if(NOT rc EQUAL 0)
            message(FATAL_ERROR "object-gates.cmake: ${TOOL} ${obj} failed: ${err}")
        endif()
        split_lines("${raw}" raw_lines)
        set(dem_lines "${raw_lines}")
        list(LENGTH raw_lines n)
        set(segs "")
        set(in_segs OFF)
        set(in_syms OFF)
        set(in_sym OFF)
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            list(GET raw_lines ${i} line)
            list(GET dem_lines ${i} dline)
            if(line MATCHES "^ *Segments <lb>")
                set(in_segs ON)
                continue()
            endif()
            if(in_segs)
                if(line MATCHES "^ *<rb>$")
                    set(in_segs OFF)
                elseif(line MATCHES "^ *Name: (.*)$")
                    list(APPEND segs "${CMAKE_MATCH_1}")
                endif()
                continue()
            endif()
            if(line MATCHES "^Symbols <lb>")
                set(in_syms ON)
                continue()
            endif()
            if(NOT in_syms)
                continue()
            endif()
            if(line MATCHES "^  Symbol \\{")
                set(in_sym ON)
                set(s_name "")
                set(s_dname "")
                set(s_undef OFF)
                set(s_local OFF)
                set(s_seg "")
                continue()
            endif()
            if(in_sym AND line MATCHES "^  \\}")
                set(in_sym OFF)
                if(s_name MATCHES "^\\.L")
                    continue()
                endif()
                if(s_undef)
                    list(APPEND u "${s_name}")
                    list(APPEND ud "${s_dname}")
                else()
                    if(NOT s_local)
                        list(APPEND d "${s_name}")
                    endif()
                    if(NOT s_seg STREQUAL "")
                        math(EXPR idx "0x${s_seg}" OUTPUT_FORMAT DECIMAL)
                        list(LENGTH segs nsegs)
                        if(NOT idx LESS nsegs)
                            message(FATAL_ERROR "object-gates.cmake: ${obj}: symbol ${s_name} names segment ${idx} of ${nsegs}")
                        endif()
                        list(GET segs ${idx} segname)
                        if(NOT segname MATCHES "^\\.(rodata|data\\.rel\\.ro)(\\.|$)")
                            list(APPEND w "${s_name}")
                            list(APPEND wd "${s_dname}")
                            list(APPEND ws "${segname}")
                        endif()
                    endif()
                endif()
                continue()
            endif()
            if(in_sym)
                if(s_name STREQUAL "" AND line MATCHES "^    Name: (.*)$")
                    set(s_name "${CMAKE_MATCH_1}")
                    if(dline MATCHES "^    Name: (.*)$")
                        set(s_dname "${CMAKE_MATCH_1}")
                    endif()
                elseif(line MATCHES "UNDEFINED \\(")
                    set(s_undef ON)
                elseif(line MATCHES "BINDING_LOCAL \\(")
                    set(s_local ON)
                elseif(line MATCHES "^    Segment: 0x([0-9A-Fa-f]+)$")
                    set(s_seg "${CMAKE_MATCH_1}")
                endif()
            endif()
        endforeach()
    endif()
    if(FORMAT STREQUAL "wasm")
        get_filename_component(tooldir "${TOOL}" DIRECTORY)
        find_program(cxxfilt NAMES llvm-cxxfilt HINTS "${tooldir}" NO_DEFAULT_PATH)
        if(NOT cxxfilt)
            message(FATAL_ERROR "object-gates.cmake: no llvm-cxxfilt beside ${TOOL} to demangle a wasm object's names")
        endif()
        foreach(v ud wd)
            if(${v})
                execute_process(COMMAND "${cxxfilt}" ${${v}} RESULT_VARIABLE rc OUTPUT_VARIABLE demangled ERROR_VARIABLE err)
                if(NOT rc EQUAL 0)
                    message(FATAL_ERROR "object-gates.cmake: ${cxxfilt} failed: ${err}")
                endif()
                string(REGEX REPLACE "\n$" "" demangled "${demangled}")
                split_lines("${demangled}" dlist)
                list(LENGTH ${v} want)
                list(LENGTH dlist got)
                if(NOT want EQUAL got)
                    message(FATAL_ERROR "object-gates.cmake: ${cxxfilt} returned ${got} names for ${want}")
                endif()
                set(${v} "${dlist}")
            endif()
        endforeach()
    endif()
    foreach(v u ud w wd ws d)
        set(o_${v} "${${v}}" PARENT_SCOPE)
    endforeach()
endfunction()

# THE NAMES A CONTROL'S EXPECTATION MAY MATCH, each in full: the raw symbol, the raw symbol less Mach-O's underscore or
# less COFF's `__imp_` (the import-table entry of a function called from a DLL: `__imp_fopen` is fopen), the demangled
# name, its last identifier (`...::lambdaCounter` of a static local), and the identifier before its parameter list
# (`to_string` of `std::__1::to_string(double)`). A control names a whole symbol, not a fragment of one.
function(name_candidates raw dem out)
    set(c "${raw}" "${dem}")
    if(raw MATCHES "^__imp_(.*)$")
        list(APPEND c "${CMAKE_MATCH_1}")
    elseif(raw MATCHES "^_(.*)$")
        list(APPEND c "${CMAKE_MATCH_1}")
    endif()
    string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_]*" ids "${dem}")
    if(ids)
        list(GET ids -1 lastid)
        list(APPEND c "${lastid}")
    endif()
    string(FIND "${dem}" "(" paren)
    if(paren GREATER 0)
        string(SUBSTRING "${dem}" 0 ${paren} head)
        string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_]*" hids "${head}")
        if(hids)
            list(GET hids -1 fnid)
            list(APPEND c "${fnid}")
        endif()
    endif()
    set(${out} "${c}" PARENT_SCOPE)
endfunction()

# ---- all objects -----------------------------------------------------------------------------------------------------
file(STRINGS "${OBJECTS_FILE}" entries REGEX "^(library|facade)\\|")
if(NOT entries)
    message(FATAL_ERROR "object-gates.cmake: ${OBJECTS_FILE} names no object — a gate over nothing reads as a pass")
endif()
set(all_defined "")
set(n_objects 0)
foreach(e IN LISTS entries)
    string(REGEX MATCH "^([a-z]+)\\|(.*)$" _ "${e}")
    set(role "${CMAKE_MATCH_1}")
    set(obj "${CMAKE_MATCH_2}")
    if(NOT EXISTS "${obj}")
        message(FATAL_ERROR "object-gates.cmake: ${obj} does not exist — build before testing")
    endif()
    math(EXPR n_objects "${n_objects} + 1")
    read_object("${obj}")
    list(APPEND all_defined ${o_d})
    set(obj_${n_objects}_role "${role}")
    set(obj_${n_objects}_path "${obj}")
    foreach(v u ud w wd ws)
        set(obj_${n_objects}_${v} "${o_${v}}")
    endforeach()
endforeach()

set(violations "")
set(violating_names "")
set(n_writable 0)
set(n_undef 0)
foreach(g IN LISTS globals)
    set(found_${g} 0)
endforeach()
foreach(k RANGE 1 ${n_objects})
    set(role "${obj_${k}_role}")
    get_filename_component(short "${obj_${k}_path}" NAME)
    # WRITABLE
    list(LENGTH obj_${k}_w nw)
    if(nw GREATER 0)
        math(EXPR lastw "${nw} - 1")
        foreach(i RANGE ${lastw})
            list(GET obj_${k}_w ${i} name)
            list(GET obj_${k}_wd ${i} dname)
            list(GET obj_${k}_ws ${i} sec)
            math(EXPR n_writable "${n_writable} + 1")
            set(ok OFF)
            if(role STREQUAL "facade")
                foreach(g IN LISTS globals)
                    # by the demangled name, or — where the reader does not demangle (llvm-readobj on wasm) — by the
                    # Itanium name's own length prefix, so `7g_slots` matches g_slots and not g_slotsExtra
                    string(LENGTH "${g}" glen)
                    if(dname MATCHES "(^|[:' ])${g}($|[^A-Za-z0-9_])" OR name MATCHES "${glen}${g}(E|$)")
                        math(EXPR found_${g} "${found_${g}} + 1")
                        set(ok ON)
                    endif()
                endforeach()
            endif()
            foreach(p IN LISTS writable_all)
                if(name MATCHES "${p}")
                    set(ok ON)
                endif()
            endforeach()
            if(NOT ok)
                list(APPEND violations "[WRITABLE] ${short}: `${dname}` (${name}) lives in ${sec} — state with static storage duration that the code can change")
                name_candidates("${name}" "${dname}" cands)
                list(APPEND violating_names ${cands})
            endif()
        endforeach()
    endif()
    # CALLED
    list(LENGTH obj_${k}_u nu)
    if(nu GREATER 0)
        math(EXPR lastu "${nu} - 1")
        foreach(i RANGE ${lastu})
            list(GET obj_${k}_u ${i} name)
            list(GET obj_${k}_ud ${i} dname)
            math(EXPR n_undef "${n_undef} + 1")
            list(FIND all_defined "${name}" defined_here)
            if(NOT defined_here EQUAL -1)
                continue()
            endif()
            set(ok OFF)
            foreach(p IN LISTS undef_all)
                if(name MATCHES "${p}")
                    set(ok ON)
                endif()
            endforeach()
            if(role STREQUAL "facade")
                foreach(p IN LISTS undef_facade)
                    if(name MATCHES "${p}")
                        set(ok ON)
                    endif()
                endforeach()
            endif()
            if(NOT ok)
                list(APPEND violations "[CALLED] ${short}: `${dname}` (${name}) — reached outside the library and not on the list in tools/lint/session-objects.txt")
                name_candidates("${name}" "${dname}" cands)
                list(APPEND violating_names ${cands})
            endif()
        endforeach()
    endif()
endforeach()

# Each allowance names something that is there, exactly once — when there is a facade object to find it in.
set(have_facade OFF)
foreach(k RANGE 1 ${n_objects})
    if(obj_${k}_role STREQUAL "facade")
        set(have_facade ON)
    endif()
endforeach()
if(have_facade)
    foreach(g IN LISTS globals)
        if(NOT found_${g} EQUAL 1)
            list(APPEND violations "[ALLOWANCE] the facade's global `${g}` was found ${found_${g}} time(s) in its objects — an allowance must name exactly one symbol that is there")
            list(APPEND violating_names "${g}")
        endif()
    endforeach()
endif()

string(REPLACE ";" "\n  " report "${violations}")
string(REPLACE "<lb>" "[" report "${report}")
string(REPLACE "<rb>" "]" report "${report}")
set(summary "${n_objects} object(s), ${n_writable} writable symbol(s), ${n_undef} called symbol(s) read with ${TOOL} (${FORMAT})")
if(DEFINED EXPECT AND NOT EXPECT STREQUAL "")
    if(NOT violations)
        message(FATAL_ERROR "CONTROL FAILED: the gate PASSED a planted violation — ${summary}")
    endif()
    string(REPLACE "&&&" ";" expects "${EXPECT}")
    foreach(re IN LISTS expects)
        set(hit OFF)
        foreach(v IN LISTS violating_names)
            if(v MATCHES "^(${re})$")
                set(hit ON)
            endif()
        endforeach()
        if(NOT hit)
            message(FATAL_ERROR "CONTROL FAILED: the gate refused, but named no symbol that is /^(${re})$/ in full:\n  ${report}")
        endif()
    endforeach()
    message(STATUS "control ok: the gate refuses the plant — ${summary}:\n  ${report}")
    return()
endif()
if(violations)
    message(FATAL_ERROR "felitronics::session object-file gate: ${summary}:\n  ${report}")
endif()
message(STATUS "felitronics::session object-file gate: clean — ${summary}")
